[project]
id = "proestimate-ai"

[auth]
site_url = "https://mhpestimate.cloud"
additional_redirect_urls = ["https://mhpestimate.cloud/**"]

[api]
port = 54321

[db]
port = 54322

[studio]
port = 54323
