// ── Demo Data Kill Switch ──
// Flip to false to remove all demo data from every page
export const DEMO_MODE = true;

// ── Date Helpers (keep data fresh) ──
function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

function daysFromNow(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString();
}

function dateOnly(iso: string): string {
  return iso.split("T")[0]!;
}

// ── Shared IDs (cross-referenced) ──
const CLIENT_IDS = [
  "demo-cli-001", "demo-cli-002", "demo-cli-003", "demo-cli-004",
  "demo-cli-005", "demo-cli-006", "demo-cli-007", "demo-cli-008",
] as const;

const ESTIMATE_IDS = [
  "demo-est-001", "demo-est-002", "demo-est-003", "demo-est-004",
  "demo-est-005", "demo-est-006", "demo-est-007", "demo-est-008",
  "demo-est-009", "demo-est-010", "demo-est-011", "demo-est-012",
] as const;

const SUB_IDS = [
  "demo-sub-001", "demo-sub-002", "demo-sub-003", "demo-sub-004", "demo-sub-005",
] as const;

// ── Clients ──
export const demoClients = [
  {
    id: CLIENT_IDS[0], organization_id: "demo-org", full_name: "Marcus Johnson",
    email: "marcus.johnson@gmail.com", phone: "(601) 555-0142",
    address_line1: "412 Meadowbrook Rd", address_line2: null,
    city: "Jackson", state: "MS", zip: "39206",
    notes: "Referred by Delta Plumbing. Wants full kitchen remodel before Thanksgiving.",
    source: "referral", created_at: daysAgo(45), updated_at: daysAgo(3),
  },
  {
    id: CLIENT_IDS[1], organization_id: "demo-org", full_name: "Sandra Williams",
    email: "sandra.w@outlook.com", phone: "(601) 555-0287",
    address_line1: "1809 Lakeland Dr", address_line2: "Suite B",
    city: "Jackson", state: "MS", zip: "39216",
    notes: "Commercial tenant build-out. Needs ADA compliance.",
    source: "website", created_at: daysAgo(38), updated_at: daysAgo(10),
  },
  {
    id: CLIENT_IDS[2], organization_id: "demo-org", full_name: "Robert & Lisa Chen",
    email: "rchen@chenlaw.com", phone: "(601) 555-0364",
    address_line1: "2250 Old Canton Rd", address_line2: null,
    city: "Brandon", state: "MS", zip: "39042",
    notes: "New construction home. Very detail-oriented. Wants weekly progress reports.",
    source: "manual", created_at: daysAgo(60), updated_at: daysAgo(5),
  },
  {
    id: CLIENT_IDS[3], organization_id: "demo-org", full_name: "Dwayne Mitchell",
    email: "d.mitchell@hotmail.com", phone: "(662) 555-0198",
    address_line1: "734 Jefferson Ave", address_line2: null,
    city: "Tupelo", state: "MS", zip: "38801",
    notes: "Garage conversion to ADU. Budget conscious.",
    source: "voice", created_at: daysAgo(22), updated_at: daysAgo(2),
  },
  {
    id: CLIENT_IDS[4], organization_id: "demo-org", full_name: "Patricia Holloway",
    email: "pholloway@gmail.com", phone: "(228) 555-0455",
    address_line1: "118 Beach Blvd", address_line2: null,
    city: "Biloxi", state: "MS", zip: "39530",
    notes: "Storm damage repair. Insurance claim in progress.",
    source: "referral", created_at: daysAgo(15), updated_at: daysAgo(1),
  },
  {
    id: CLIENT_IDS[5], organization_id: "demo-org", full_name: "James Earl Davis",
    email: "jedavis@yahoo.com", phone: "(601) 555-0533",
    address_line1: "3901 Hardy St", address_line2: null,
    city: "Hattiesburg", state: "MS", zip: "39402",
    notes: "Master bathroom renovation. Wants walk-in shower with frameless glass.",
    source: "website", created_at: daysAgo(30), updated_at: daysAgo(7),
  },
  {
    id: CLIENT_IDS[6], organization_id: "demo-org", full_name: "Angela Foster",
    email: "angela.foster@gmail.com", phone: "(601) 555-0611",
    address_line1: "502 University Ave", address_line2: null,
    city: "Oxford", state: "MS", zip: "38655",
    notes: "Historic home restoration. Must maintain period character.",
    source: "referral", created_at: daysAgo(52), updated_at: daysAgo(14),
  },
  {
    id: CLIENT_IDS[7], organization_id: "demo-org", full_name: "Tony Nguyen",
    email: "tony.n@gmail.com", phone: "(228) 555-0789",
    address_line1: "2100 Pass Rd", address_line2: null,
    city: "Gulfport", state: "MS", zip: "39501",
    notes: "Restaurant build-out. Tight timeline — lease starts next month.",
    source: "manual", created_at: daysAgo(8), updated_at: daysAgo(1),
  },
] as const;

// ── Estimates ──
export const demoEstimates = [
  {
    id: ESTIMATE_IDS[0], organization_id: "demo-org", estimate_number: "MHP-2026-001",
    client_id: CLIENT_IDS[0], estimator_id: null, reviewer_id: null,
    project_type: "Kitchen Remodel", estimate_category: "building" as const,
    foundation_type: null, foundation_block_height: null,
    square_footage: 280, project_address: "412 Meadowbrook Rd, Jackson, MS 39206",
    status: "accepted" as const,
    scope_inclusions: ["Demo existing cabinets", "New cabinetry", "Granite countertops", "Tile backsplash", "Plumbing fixtures"],
    scope_exclusions: ["Appliances", "Flooring outside kitchen"],
    site_conditions: "Load-bearing wall on north side — needs temp support during demo",
    materials_subtotal: 18500, labor_subtotal: 14200, subcontractor_total: 3800,
    retail_total: 42500, actual_total: 38900, permits_fees: 450,
    overhead_profit: 5200, contingency: 1950, tax: 2870,
    grand_total: 47850, cost_per_sqft: 170.89, gross_margin_pct: 38.2,
    estimated_start: dateOnly(daysAgo(10)), estimated_end: dateOnly(daysFromNow(25)),
    valid_through: dateOnly(daysFromNow(30)),
    tier: "midrange" as const, source: "manual" as const,
    call_id: null, validation_results: null, validation_passed: true,
    pdf_path: null, docx_path: null, version: 1, parent_estimate_id: null,
    zip_code: "39206", win_score: 82, win_score_updated_at: daysAgo(5),
    created_at: daysAgo(42), updated_at: daysAgo(3),
    sent_at: daysAgo(38), accepted_at: daysAgo(10), declined_at: null,
  },
  {
    id: ESTIMATE_IDS[1], organization_id: "demo-org", estimate_number: "MHP-2026-002",
    client_id: CLIENT_IDS[1], estimator_id: null, reviewer_id: null,
    project_type: "Commercial Tenant Build-Out", estimate_category: "building" as const,
    foundation_type: null, foundation_block_height: null,
    square_footage: 1800, project_address: "1809 Lakeland Dr Suite B, Jackson, MS 39216",
    status: "sent" as const,
    scope_inclusions: ["Framing", "Drywall", "Electrical", "Plumbing", "HVAC mods", "ADA restroom"],
    scope_exclusions: ["Exterior work", "Signage"],
    site_conditions: "Existing commercial space, drop ceiling throughout",
    materials_subtotal: 42000, labor_subtotal: 38500, subcontractor_total: 22000,
    retail_total: 118000, actual_total: 108500, permits_fees: 1200,
    overhead_profit: 15800, contingency: 5400, tax: 7950,
    grand_total: 142500, cost_per_sqft: 79.17, gross_margin_pct: 34.5,
    estimated_start: dateOnly(daysFromNow(14)), estimated_end: dateOnly(daysFromNow(75)),
    valid_through: dateOnly(daysFromNow(21)),
    tier: "midrange" as const, source: "manual" as const,
    call_id: null, validation_results: null, validation_passed: true,
    pdf_path: null, docx_path: null, version: 1, parent_estimate_id: null,
    zip_code: "39216", win_score: 65, win_score_updated_at: daysAgo(2),
    created_at: daysAgo(35), updated_at: daysAgo(2),
    sent_at: daysAgo(5), accepted_at: null, declined_at: null,
  },
  {
    id: ESTIMATE_IDS[2], organization_id: "demo-org", estimate_number: "MHP-2026-003",
    client_id: CLIENT_IDS[2], estimator_id: null, reviewer_id: null,
    project_type: "Whole House Renovation", estimate_category: "building" as const,
    foundation_type: "crawlspace" as const, foundation_block_height: null,
    square_footage: 2400, project_address: "2250 Old Canton Rd, Brandon, MS 39042",
    status: "approved" as const,
    scope_inclusions: ["Full gut renovation", "New roof", "HVAC replacement", "Electrical upgrade", "Plumbing", "Finishes"],
    scope_exclusions: ["Landscaping", "Pool"],
    site_conditions: "1960s ranch. Possible asbestos in popcorn ceiling — test before demo.",
    materials_subtotal: 58000, labor_subtotal: 52000, subcontractor_total: 28000,
    retail_total: 165000, actual_total: 148200, permits_fees: 2800,
    overhead_profit: 22000, contingency: 8250, tax: 11100,
    grand_total: 185000, cost_per_sqft: 77.08, gross_margin_pct: 42.1,
    estimated_start: dateOnly(daysFromNow(30)), estimated_end: dateOnly(daysFromNow(150)),
    valid_through: dateOnly(daysFromNow(45)),
    tier: "high_end" as const, source: "manual" as const,
    call_id: null, validation_results: null, validation_passed: true,
    pdf_path: null, docx_path: null, version: 2, parent_estimate_id: null,
    zip_code: "39042", win_score: 91, win_score_updated_at: daysAgo(3),
    created_at: daysAgo(55), updated_at: daysAgo(5),
    sent_at: daysAgo(50), accepted_at: null, declined_at: null,
  },
  {
    id: ESTIMATE_IDS[3], organization_id: "demo-org", estimate_number: "MHP-2026-004",
    client_id: CLIENT_IDS[3], estimator_id: null, reviewer_id: null,
    project_type: "Garage Conversion (ADU)", estimate_category: "building" as const,
    foundation_type: "monolithic_slab" as const, foundation_block_height: null,
    square_footage: 480, project_address: "734 Jefferson Ave, Tupelo, MS 38801",
    status: "draft" as const,
    scope_inclusions: ["Insulation", "Drywall", "Electrical", "Mini-split HVAC", "Kitchenette", "Bathroom"],
    scope_exclusions: ["Garage door removal by owner"],
    site_conditions: "Two-car garage, concrete slab in good condition",
    materials_subtotal: 12800, labor_subtotal: 11500, subcontractor_total: 4200,
    retail_total: 34000, actual_total: 31200, permits_fees: 650,
    overhead_profit: 4500, contingency: 1560, tax: 2380,
    grand_total: 38500, cost_per_sqft: 80.21, gross_margin_pct: 32.8,
    estimated_start: null, estimated_end: null,
    valid_through: null,
    tier: "budget" as const, source: "voice" as const,
    call_id: null, validation_results: null, validation_passed: false,
    pdf_path: null, docx_path: null, version: 1, parent_estimate_id: null,
    zip_code: "38801", win_score: null, win_score_updated_at: null,
    created_at: daysAgo(18), updated_at: daysAgo(2),
    sent_at: null, accepted_at: null, declined_at: null,
  },
  {
    id: ESTIMATE_IDS[4], organization_id: "demo-org", estimate_number: "MHP-2026-005",
    client_id: CLIENT_IDS[4], estimator_id: null, reviewer_id: null,
    project_type: "Storm Damage Roof Repair", estimate_category: "building" as const,
    foundation_type: null, foundation_block_height: null,
    square_footage: 2200, project_address: "118 Beach Blvd, Biloxi, MS 39530",
    status: "accepted" as const,
    scope_inclusions: ["Tear-off existing shingles", "Replace decking", "Ice & water shield", "Architectural shingles", "Ridge vent"],
    scope_exclusions: ["Gutters", "Interior water damage"],
    site_conditions: "Two-story. Steep pitch on south face. Hurricane clips required.",
    materials_subtotal: 9800, labor_subtotal: 8400, subcontractor_total: 0,
    retail_total: 22000, actual_total: 19800, permits_fees: 350,
    overhead_profit: 2800, contingency: 990, tax: 1360,
    grand_total: 24200, cost_per_sqft: 11.0, gross_margin_pct: 35.6,
    estimated_start: dateOnly(daysAgo(5)), estimated_end: dateOnly(daysFromNow(10)),
    valid_through: dateOnly(daysFromNow(14)),
    tier: "midrange" as const, source: "manual" as const,
    call_id: null, validation_results: null, validation_passed: true,
    pdf_path: null, docx_path: null, version: 1, parent_estimate_id: null,
    zip_code: "39530", win_score: 88, win_score_updated_at: daysAgo(8),
    created_at: daysAgo(14), updated_at: daysAgo(1),
    sent_at: daysAgo(12), accepted_at: daysAgo(8), declined_at: null,
  },
  {
    id: ESTIMATE_IDS[5], organization_id: "demo-org", estimate_number: "MHP-2026-006",
    client_id: CLIENT_IDS[5], estimator_id: null, reviewer_id: null,
    project_type: "Master Bathroom Renovation", estimate_category: "building" as const,
    foundation_type: null, foundation_block_height: null,
    square_footage: 120, project_address: "3901 Hardy St, Hattiesburg, MS 39402",
    status: "sent" as const,
    scope_inclusions: ["Demo existing bath", "Walk-in shower", "Frameless glass", "Heated floors", "Double vanity"],
    scope_exclusions: ["Master bedroom work"],
    site_conditions: "Second floor. Joists in good shape per inspection.",
    materials_subtotal: 11200, labor_subtotal: 9800, subcontractor_total: 2400,
    retail_total: 28000, actual_total: 25600, permits_fees: 280,
    overhead_profit: 3600, contingency: 1280, tax: 1740,
    grand_total: 32400, cost_per_sqft: 270.0, gross_margin_pct: 36.8,
    estimated_start: dateOnly(daysFromNow(20)), estimated_end: dateOnly(daysFromNow(50)),
    valid_through: dateOnly(daysFromNow(30)),
    tier: "high_end" as const, source: "manual" as const,
    call_id: null, validation_results: null, validation_passed: true,
    pdf_path: null, docx_path: null, version: 1, parent_estimate_id: null,
    zip_code: "39402", win_score: 72, win_score_updated_at: daysAgo(4),
    created_at: daysAgo(28), updated_at: daysAgo(4),
    sent_at: daysAgo(7), accepted_at: null, declined_at: null,
  },
  {
    id: ESTIMATE_IDS[6], organization_id: "demo-org", estimate_number: "MHP-2026-007",
    client_id: CLIENT_IDS[6], estimator_id: null, reviewer_id: null,
    project_type: "Historic Home Restoration", estimate_category: "building" as const,
    foundation_type: "pier_beam" as const, foundation_block_height: null,
    square_footage: 1600, project_address: "502 University Ave, Oxford, MS 38655",
    status: "in_review" as const,
    scope_inclusions: ["Foundation repair", "Wood siding restoration", "Window restoration", "Interior plaster repair"],
    scope_exclusions: ["Paint (separate bid)", "HVAC"],
    site_conditions: "1920s Craftsman. Some original heart pine flooring salvageable.",
    materials_subtotal: 34000, labor_subtotal: 42000, subcontractor_total: 8500,
    retail_total: 102000, actual_total: 92500, permits_fees: 1800,
    overhead_profit: 12500, contingency: 5100, tax: 7100,
    grand_total: 118500, cost_per_sqft: 74.06, gross_margin_pct: 40.2,
    estimated_start: dateOnly(daysFromNow(45)), estimated_end: dateOnly(daysFromNow(165)),
    valid_through: dateOnly(daysFromNow(30)),
    tier: "high_end" as const, source: "manual" as const,
    call_id: null, validation_results: null, validation_passed: true,
    pdf_path: null, docx_path: null, version: 1, parent_estimate_id: null,
    zip_code: "38655", win_score: 58, win_score_updated_at: daysAgo(1),
    created_at: daysAgo(12), updated_at: daysAgo(1),
    sent_at: null, accepted_at: null, declined_at: null,
  },
  {
    id: ESTIMATE_IDS[7], organization_id: "demo-org", estimate_number: "MHP-2026-008",
    client_id: CLIENT_IDS[7], estimator_id: null, reviewer_id: null,
    project_type: "Restaurant Build-Out", estimate_category: "building" as const,
    foundation_type: null, foundation_block_height: null,
    square_footage: 2800, project_address: "2100 Pass Rd, Gulfport, MS 39501",
    status: "draft" as const,
    scope_inclusions: ["Commercial kitchen rough-in", "Hood system", "Walk-in cooler pad", "Dining area finishes", "ADA restrooms"],
    scope_exclusions: ["Kitchen equipment", "Signage", "Furniture"],
    site_conditions: "Former retail space. Grease trap needed.",
    materials_subtotal: 48000, labor_subtotal: 44000, subcontractor_total: 18000,
    retail_total: 132000, actual_total: 118500, permits_fees: 3200,
    overhead_profit: 16500, contingency: 6600, tax: 8900,
    grand_total: 155000, cost_per_sqft: 55.36, gross_margin_pct: 28.4,
    estimated_start: null, estimated_end: null,
    valid_through: null,
    tier: "midrange" as const, source: "manual" as const,
    call_id: null, validation_results: null, validation_passed: false,
    pdf_path: null, docx_path: null, version: 1, parent_estimate_id: null,
    zip_code: "39501", win_score: null, win_score_updated_at: null,
    created_at: daysAgo(6), updated_at: daysAgo(1),
    sent_at: null, accepted_at: null, declined_at: null,
  },
  {
    id: ESTIMATE_IDS[8], organization_id: "demo-org", estimate_number: "MHP-2026-009",
    client_id: CLIENT_IDS[0], estimator_id: null, reviewer_id: null,
    project_type: "Deck Addition", estimate_category: "building" as const,
    foundation_type: null, foundation_block_height: null,
    square_footage: 320, project_address: "412 Meadowbrook Rd, Jackson, MS 39206",
    status: "approved" as const,
    scope_inclusions: ["Pressure-treated framing", "Composite decking", "Railing system", "LED stair lights"],
    scope_exclusions: ["Pergola", "Outdoor kitchen"],
    site_conditions: "Flat backyard, good drainage. HOA approved.",
    materials_subtotal: 6800, labor_subtotal: 5200, subcontractor_total: 0,
    retail_total: 14500, actual_total: 13200, permits_fees: 200,
    overhead_profit: 1800, contingency: 650, tax: 950,
    grand_total: 16800, cost_per_sqft: 52.5, gross_margin_pct: 38.5,
    estimated_start: dateOnly(daysFromNow(35)), estimated_end: dateOnly(daysFromNow(50)),
    valid_through: dateOnly(daysFromNow(30)),
    tier: "midrange" as const, source: "voice" as const,
    call_id: null, validation_results: null, validation_passed: true,
    pdf_path: null, docx_path: null, version: 1, parent_estimate_id: null,
    zip_code: "39206", win_score: 78, win_score_updated_at: daysAgo(6),
    created_at: daysAgo(25), updated_at: daysAgo(6),
    sent_at: daysAgo(20), accepted_at: null, declined_at: null,
  },
  {
    id: ESTIMATE_IDS[9], organization_id: "demo-org", estimate_number: "MHP-2026-010",
    client_id: CLIENT_IDS[3], estimator_id: null, reviewer_id: null,
    project_type: "Interior Paint (Whole House)", estimate_category: "building" as const,
    foundation_type: null, foundation_block_height: null,
    square_footage: 1800, project_address: "734 Jefferson Ave, Tupelo, MS 38801",
    status: "declined" as const,
    scope_inclusions: ["Prep & prime all walls", "2 coats Sherwin-Williams Duration", "Trim & doors", "Ceiling touch-up"],
    scope_exclusions: ["Wallpaper removal", "Exterior"],
    site_conditions: "Occupied home. Work around furniture.",
    materials_subtotal: 1200, labor_subtotal: 2800, subcontractor_total: 0,
    retail_total: 4800, actual_total: 4200, permits_fees: 0,
    overhead_profit: 600, contingency: 200, tax: 290,
    grand_total: 3500, cost_per_sqft: 1.94, gross_margin_pct: 29.4,
    estimated_start: null, estimated_end: null,
    valid_through: dateOnly(daysAgo(5)),
    tier: "budget" as const, source: "voice" as const,
    call_id: null, validation_results: null, validation_passed: true,
    pdf_path: null, docx_path: null, version: 1, parent_estimate_id: null,
    zip_code: "38801", win_score: 25, win_score_updated_at: daysAgo(10),
    created_at: daysAgo(30), updated_at: daysAgo(10),
    sent_at: daysAgo(28), accepted_at: null, declined_at: daysAgo(10),
  },
  {
    id: ESTIMATE_IDS[10], organization_id: "demo-org", estimate_number: "MHP-2026-011",
    client_id: CLIENT_IDS[5], estimator_id: null, reviewer_id: null,
    project_type: "Laundry Room Remodel", estimate_category: "building" as const,
    foundation_type: null, foundation_block_height: null,
    square_footage: 80, project_address: "3901 Hardy St, Hattiesburg, MS 39402",
    status: "in_review" as const,
    scope_inclusions: ["New cabinetry", "Utility sink", "Tile flooring", "Countertop"],
    scope_exclusions: ["Appliances"],
    site_conditions: "First floor. Water heater nearby — protect during work.",
    materials_subtotal: 3200, labor_subtotal: 2800, subcontractor_total: 800,
    retail_total: 8200, actual_total: 7400, permits_fees: 120,
    overhead_profit: 1050, contingency: 380, tax: 530,
    grand_total: 9200, cost_per_sqft: 115.0, gross_margin_pct: 33.6,
    estimated_start: null, estimated_end: null,
    valid_through: null,
    tier: "midrange" as const, source: "manual" as const,
    call_id: null, validation_results: null, validation_passed: true,
    pdf_path: null, docx_path: null, version: 1, parent_estimate_id: null,
    zip_code: "39402", win_score: null, win_score_updated_at: null,
    created_at: daysAgo(5), updated_at: daysAgo(1),
    sent_at: null, accepted_at: null, declined_at: null,
  },
  {
    id: ESTIMATE_IDS[11], organization_id: "demo-org", estimate_number: "MHP-2026-012",
    client_id: CLIENT_IDS[4], estimator_id: null, reviewer_id: null,
    project_type: "Siding Replacement", estimate_category: "building" as const,
    foundation_type: null, foundation_block_height: null,
    square_footage: 1900, project_address: "118 Beach Blvd, Biloxi, MS 39530",
    status: "draft" as const,
    scope_inclusions: ["Remove damaged vinyl siding", "Housewrap", "James Hardie fiber cement", "Trim"],
    scope_exclusions: ["Painting (included in siding)", "Window replacement"],
    site_conditions: "Coastal zone. Impact-rated materials required.",
    materials_subtotal: 14200, labor_subtotal: 10800, subcontractor_total: 0,
    retail_total: 30000, actual_total: 27200, permits_fees: 380,
    overhead_profit: 3800, contingency: 1350, tax: 1870,
    grand_total: 32500, cost_per_sqft: 17.11, gross_margin_pct: 31.2,
    estimated_start: null, estimated_end: null,
    valid_through: null,
    tier: "midrange" as const, source: "manual" as const,
    call_id: null, validation_results: null, validation_passed: false,
    pdf_path: null, docx_path: null, version: 1, parent_estimate_id: null,
    zip_code: "39530", win_score: null, win_score_updated_at: null,
    created_at: daysAgo(3), updated_at: daysAgo(1),
    sent_at: null, accepted_at: null, declined_at: null,
  },
];

// ── Job Phases (for SchedulePage) ──
export const demoJobPhases = [
  // Kitchen Remodel phases (EST-001)
  { id: "demo-jp-01", estimate_id: ESTIMATE_IDS[0], phase_name: "Demolition", sort_order: 0, start_date: dateOnly(daysAgo(10)), end_date: dateOnly(daysAgo(7)), status: "completed", crew_assigned: ["Marcus T.", "Devon L."], notes: "Dumpster delivered day 1", color: "#ef4444", actual_start: dateOnly(daysAgo(10)), actual_end: dateOnly(daysAgo(7)), created_at: daysAgo(12) },
  { id: "demo-jp-02", estimate_id: ESTIMATE_IDS[0], phase_name: "Rough Plumbing", sort_order: 1, start_date: dateOnly(daysAgo(6)), end_date: dateOnly(daysAgo(4)), status: "completed", crew_assigned: ["Delta Plumbing"], notes: null, color: "#3b82f6", actual_start: dateOnly(daysAgo(6)), actual_end: dateOnly(daysAgo(4)), created_at: daysAgo(12) },
  { id: "demo-jp-03", estimate_id: ESTIMATE_IDS[0], phase_name: "Electrical Rough-In", sort_order: 2, start_date: dateOnly(daysAgo(5)), end_date: dateOnly(daysAgo(3)), status: "completed", crew_assigned: ["Southern Electric"], notes: "Added 2 extra circuits per client request", color: "#f59e0b", actual_start: dateOnly(daysAgo(5)), actual_end: dateOnly(daysAgo(3)), created_at: daysAgo(12) },
  { id: "demo-jp-04", estimate_id: ESTIMATE_IDS[0], phase_name: "Drywall & Tape", sort_order: 3, start_date: dateOnly(daysAgo(2)), end_date: dateOnly(daysFromNow(1)), status: "in_progress", crew_assigned: ["Dixie Drywall"], notes: null, color: "#8b5cf6", actual_start: dateOnly(daysAgo(2)), actual_end: null, created_at: daysAgo(12) },
  { id: "demo-jp-05", estimate_id: ESTIMATE_IDS[0], phase_name: "Cabinet Install", sort_order: 4, start_date: dateOnly(daysFromNow(3)), end_date: dateOnly(daysFromNow(6)), status: "not_started", crew_assigned: ["Marcus T.", "Devon L."], notes: "Cabinets arriving from supplier Tues", color: "#10b981", actual_start: null, actual_end: null, created_at: daysAgo(12) },
  { id: "demo-jp-06", estimate_id: ESTIMATE_IDS[0], phase_name: "Countertop Template & Install", sort_order: 5, start_date: dateOnly(daysFromNow(8)), end_date: dateOnly(daysFromNow(14)), status: "not_started", crew_assigned: ["Magnolia Concrete"], notes: "Template after cabinets set. 5-day fabrication.", color: "#6366f1", actual_start: null, actual_end: null, created_at: daysAgo(12) },
  { id: "demo-jp-07", estimate_id: ESTIMATE_IDS[0], phase_name: "Tile Backsplash", sort_order: 6, start_date: dateOnly(daysFromNow(15)), end_date: dateOnly(daysFromNow(18)), status: "not_started", crew_assigned: ["Marcus T."], notes: null, color: "#ec4899", actual_start: null, actual_end: null, created_at: daysAgo(12) },
  { id: "demo-jp-08", estimate_id: ESTIMATE_IDS[0], phase_name: "Final Plumbing & Fixtures", sort_order: 7, start_date: dateOnly(daysFromNow(19)), end_date: dateOnly(daysFromNow(21)), status: "not_started", crew_assigned: ["Delta Plumbing"], notes: null, color: "#3b82f6", actual_start: null, actual_end: null, created_at: daysAgo(12) },
  { id: "demo-jp-09", estimate_id: ESTIMATE_IDS[0], phase_name: "Punch List & Final Walk", sort_order: 8, start_date: dateOnly(daysFromNow(22)), end_date: dateOnly(daysFromNow(25)), status: "not_started", crew_assigned: ["Marcus T."], notes: "Schedule client walkthrough", color: "#14b8a6", actual_start: null, actual_end: null, created_at: daysAgo(12) },

  // Roof Repair phases (EST-005)
  { id: "demo-jp-10", estimate_id: ESTIMATE_IDS[4], phase_name: "Tear-Off & Inspection", sort_order: 0, start_date: dateOnly(daysAgo(5)), end_date: dateOnly(daysAgo(4)), status: "completed", crew_assigned: ["Gulf Coast Roofing"], notes: "Found 3 sheets bad decking — replaced", color: "#ef4444", actual_start: dateOnly(daysAgo(5)), actual_end: dateOnly(daysAgo(4)), created_at: daysAgo(6) },
  { id: "demo-jp-11", estimate_id: ESTIMATE_IDS[4], phase_name: "Decking Repair & Ice Shield", sort_order: 1, start_date: dateOnly(daysAgo(3)), end_date: dateOnly(daysAgo(2)), status: "completed", crew_assigned: ["Gulf Coast Roofing"], notes: null, color: "#f59e0b", actual_start: dateOnly(daysAgo(3)), actual_end: dateOnly(daysAgo(2)), created_at: daysAgo(6) },
  { id: "demo-jp-12", estimate_id: ESTIMATE_IDS[4], phase_name: "Shingle Install", sort_order: 2, start_date: dateOnly(daysAgo(1)), end_date: dateOnly(daysFromNow(3)), status: "in_progress", crew_assigned: ["Gulf Coast Roofing"], notes: "Owens Corning Duration — Driftwood color", color: "#3b82f6", actual_start: dateOnly(daysAgo(1)), actual_end: null, created_at: daysAgo(6) },
  { id: "demo-jp-13", estimate_id: ESTIMATE_IDS[4], phase_name: "Ridge Vent & Flashing", sort_order: 3, start_date: dateOnly(daysFromNow(4)), end_date: dateOnly(daysFromNow(6)), status: "not_started", crew_assigned: ["Gulf Coast Roofing"], notes: null, color: "#10b981", actual_start: null, actual_end: null, created_at: daysAgo(6) },
  { id: "demo-jp-14", estimate_id: ESTIMATE_IDS[4], phase_name: "Cleanup & Insurance Photos", sort_order: 4, start_date: dateOnly(daysFromNow(7)), end_date: dateOnly(daysFromNow(8)), status: "not_started", crew_assigned: ["Marcus T."], notes: "Need before/after for adjuster", color: "#8b5cf6", actual_start: null, actual_end: null, created_at: daysAgo(6) },
  { id: "demo-jp-15", estimate_id: ESTIMATE_IDS[4], phase_name: "City Inspection", sort_order: 5, start_date: dateOnly(daysFromNow(10)), end_date: dateOnly(daysFromNow(10)), status: "blocked", crew_assigned: [], notes: "Waiting on inspector availability — called 3/14", color: "#ef4444", actual_start: null, actual_end: null, created_at: daysAgo(6) },
];

// ── Invoices ──
export const demoInvoices = [
  {
    id: "demo-inv-001", organization_id: "demo-org", supplier_name: "Home Depot",
    invoice_number: "HD-4492817", invoice_date: dateOnly(daysAgo(8)),
    file_path: "/invoices/hd-4492817.pdf", ocr_raw_text: null,
    parsed_data: { total: 3842.50, line_items: [
      { description: "KraftMaid Base Cabinet 36\"", qty: 4, unit_price: 389.00, total: 1556.00 },
      { description: "KraftMaid Wall Cabinet 30\"", qty: 6, unit_price: 279.00, total: 1674.00 },
      { description: "Cabinet Hardware Pulls (25pk)", qty: 2, unit_price: 54.99, total: 109.98 },
      { description: "Delivery Fee", qty: 1, unit_price: 79.00, total: 79.00 },
    ]},
    status: "confirmed" as const, uploaded_by: null, reviewed_by: null,
    created_at: daysAgo(8),
  },
  {
    id: "demo-inv-002", organization_id: "demo-org", supplier_name: "84 Lumber",
    invoice_number: "84L-20260228", invoice_date: dateOnly(daysAgo(12)),
    file_path: "/invoices/84l-20260228.pdf", ocr_raw_text: null,
    parsed_data: { total: 6218.75, line_items: [
      { description: "2x6 SPF #2 16' (bundle)", qty: 3, unit_price: 485.00, total: 1455.00 },
      { description: "2x4 SPF #2 8' (bundle)", qty: 4, unit_price: 298.00, total: 1192.00 },
      { description: "3/4\" CDX Plywood 4x8", qty: 24, unit_price: 52.50, total: 1260.00 },
      { description: "Tyvek Housewrap 9x150", qty: 2, unit_price: 189.00, total: 378.00 },
      { description: "Various Fasteners", qty: 1, unit_price: 445.75, total: 445.75 },
    ]},
    status: "confirmed" as const, uploaded_by: null, reviewed_by: null,
    created_at: daysAgo(12),
  },
  {
    id: "demo-inv-003", organization_id: "demo-org", supplier_name: "Ferguson Plumbing",
    invoice_number: "FERG-MS-8812", invoice_date: dateOnly(daysAgo(5)),
    file_path: "/invoices/ferg-ms-8812.pdf", ocr_raw_text: null,
    parsed_data: { total: 2156.80, line_items: [
      { description: "Delta Cassidy Kitchen Faucet", qty: 1, unit_price: 485.00, total: 485.00 },
      { description: "Kohler Vault 33\" Undermount Sink", qty: 1, unit_price: 689.00, total: 689.00 },
      { description: "PEX-A 3/4\" (100ft)", qty: 2, unit_price: 124.50, total: 249.00 },
      { description: "Misc Fittings & Valves", qty: 1, unit_price: 388.80, total: 388.80 },
    ]},
    status: "review" as const, uploaded_by: null, reviewed_by: null,
    created_at: daysAgo(5),
  },
  {
    id: "demo-inv-004", organization_id: "demo-org", supplier_name: "ABC Supply",
    invoice_number: "ABC-GC-41205", invoice_date: dateOnly(daysAgo(3)),
    file_path: "/invoices/abc-gc-41205.pdf", ocr_raw_text: null,
    parsed_data: { total: 4890.00, line_items: [
      { description: "OC Duration Shingles (Driftwood) per sq", qty: 24, unit_price: 142.00, total: 3408.00 },
      { description: "Ice & Water Shield 200sqft", qty: 3, unit_price: 185.00, total: 555.00 },
      { description: "Synthetic Underlayment 10sq", qty: 3, unit_price: 98.00, total: 294.00 },
      { description: "Ridge Vent 4' sections", qty: 8, unit_price: 18.50, total: 148.00 },
      { description: "Step Flashing Kit", qty: 2, unit_price: 42.50, total: 85.00 },
    ]},
    status: "pending" as const, uploaded_by: null, reviewed_by: null,
    created_at: daysAgo(3),
  },
  {
    id: "demo-inv-005", organization_id: "demo-org", supplier_name: "Sherwin-Williams",
    invoice_number: "SW-JAX-9942", invoice_date: dateOnly(daysAgo(15)),
    file_path: "/invoices/sw-jax-9942.pdf", ocr_raw_text: null,
    parsed_data: { total: 892.40, line_items: [
      { description: "Duration Interior Flat (5gal)", qty: 4, unit_price: 164.99, total: 659.96 },
      { description: "ProClassic Semi-Gloss Trim (gal)", qty: 3, unit_price: 62.49, total: 187.47 },
      { description: "Purdy Roller Covers (6pk)", qty: 2, unit_price: 22.49, total: 44.98 },
    ]},
    status: "confirmed" as const, uploaded_by: null, reviewed_by: null,
    created_at: daysAgo(15),
  },
  {
    id: "demo-inv-006", organization_id: "demo-org", supplier_name: "Home Depot",
    invoice_number: "HD-4501293", invoice_date: dateOnly(daysAgo(1)),
    file_path: "/invoices/hd-4501293.pdf", ocr_raw_text: null,
    parsed_data: { total: 1247.50, line_items: [
      { description: "TimberTech Composite Decking 16' (20pk)", qty: 1, unit_price: 890.00, total: 890.00 },
      { description: "Deck Screws (5lb box)", qty: 3, unit_price: 32.50, total: 97.50 },
      { description: "Post Brackets", qty: 8, unit_price: 12.50, total: 100.00 },
      { description: "Joist Hangers", qty: 16, unit_price: 3.75, total: 60.00 },
    ]},
    status: "processing" as const, uploaded_by: null, reviewed_by: null,
    created_at: daysAgo(1),
  },
];

// ── Products (for MaterialsPage) ──
export const demoProducts = [
  {
    id: "demo-prod-001", organization_id: "demo-org", name: "KraftMaid Base Cabinet 36\"",
    category: "Cabinetry", subcategory: "Base", brand: "KraftMaid", sku_hd: "KM-BC36-MP",
    sku_lowes: null, sku_internal: null, unit: "ea",
    specifications: { width: "36in", depth: "24in", material: "Maple" },
    tier: "mid" as const, is_active: true,
    created_at: daysAgo(90), updated_at: daysAgo(8),
    unified_pricing: { product_id: "demo-prod-001", organization_id: "demo-org", unified_price: 389.0, hd_price: 389.0, lowes_price: 405.0, invoice_price: null, freshness: "green" as const, last_updated: daysAgo(8) },
  },
  {
    id: "demo-prod-002", organization_id: "demo-org", name: "LVP Flooring - Driftwood Oak",
    category: "Flooring", subcategory: "LVP", brand: "LifeProof", sku_hd: "LP-DWO-7x48",
    sku_lowes: null, sku_internal: null, unit: "sqft",
    specifications: { width: "7in", length: "48in", thickness: "6mm" },
    tier: "mid" as const, is_active: true,
    created_at: daysAgo(120), updated_at: daysAgo(15),
    unified_pricing: { product_id: "demo-prod-002", organization_id: "demo-org", unified_price: 3.29, hd_price: 3.29, lowes_price: 3.49, invoice_price: null, freshness: "green" as const, last_updated: daysAgo(15) },
  },
  {
    id: "demo-prod-003", organization_id: "demo-org", name: "Granite Countertop - Luna Pearl",
    category: "Countertops", subcategory: "Granite", brand: "MSI", sku_hd: null,
    sku_lowes: null, sku_internal: "GRN-LP-3CM", unit: "sqft",
    specifications: { thickness: "3cm", finish: "Polished" },
    tier: "mid" as const, is_active: true,
    created_at: daysAgo(85), updated_at: daysAgo(30),
    unified_pricing: { product_id: "demo-prod-003", organization_id: "demo-org", unified_price: 45.0, hd_price: 48.0, lowes_price: null, invoice_price: 42.0, freshness: "yellow" as const, last_updated: daysAgo(30) },
  },
  {
    id: "demo-prod-004", organization_id: "demo-org", name: "Sherwin-Williams Duration Interior",
    category: "Paint", subcategory: "Interior", brand: "Sherwin-Williams", sku_hd: null,
    sku_lowes: null, sku_internal: "SW-DUR-INT-5G", unit: "5gal",
    specifications: { finish: "Flat", coverage: "400 sqft/gal" },
    tier: "premium" as const, is_active: true,
    created_at: daysAgo(200), updated_at: daysAgo(15),
    unified_pricing: { product_id: "demo-prod-004", organization_id: "demo-org", unified_price: 164.99, hd_price: null, lowes_price: null, invoice_price: 164.99, freshness: "green" as const, last_updated: daysAgo(15) },
  },
  {
    id: "demo-prod-005", organization_id: "demo-org", name: "OC Duration Architectural Shingles",
    category: "Roofing", subcategory: "Shingles", brand: "Owens Corning", sku_hd: "OC-DUR-DRIFT",
    sku_lowes: null, sku_internal: null, unit: "sq",
    specifications: { color: "Driftwood", warranty: "Lifetime Limited" },
    tier: "mid" as const, is_active: true,
    created_at: daysAgo(150), updated_at: daysAgo(3),
    unified_pricing: { product_id: "demo-prod-005", organization_id: "demo-org", unified_price: 142.0, hd_price: 148.0, lowes_price: 145.0, invoice_price: 142.0, freshness: "green" as const, last_updated: daysAgo(3) },
  },
  {
    id: "demo-prod-006", organization_id: "demo-org", name: "2x6 SPF #2 16'",
    category: "Lumber", subcategory: "Dimensional", brand: null, sku_hd: "SPF-2x6-16",
    sku_lowes: null, sku_internal: null, unit: "ea",
    specifications: { grade: "#2", species: "Spruce/Pine/Fir" },
    tier: "budget" as const, is_active: true,
    created_at: daysAgo(180), updated_at: daysAgo(12),
    unified_pricing: { product_id: "demo-prod-006", organization_id: "demo-org", unified_price: 8.98, hd_price: 8.98, lowes_price: 9.12, invoice_price: 8.08, freshness: "green" as const, last_updated: daysAgo(12) },
  },
  {
    id: "demo-prod-007", organization_id: "demo-org", name: "Delta Cassidy Kitchen Faucet",
    category: "Plumbing", subcategory: "Faucets", brand: "Delta", sku_hd: "DLT-CASS-9197",
    sku_lowes: null, sku_internal: null, unit: "ea",
    specifications: { finish: "Champagne Bronze", flow_rate: "1.8 GPM" },
    tier: "premium" as const, is_active: true,
    created_at: daysAgo(60), updated_at: daysAgo(5),
    unified_pricing: { product_id: "demo-prod-007", organization_id: "demo-org", unified_price: 485.0, hd_price: 485.0, lowes_price: 499.0, invoice_price: 485.0, freshness: "green" as const, last_updated: daysAgo(5) },
  },
  {
    id: "demo-prod-008", organization_id: "demo-org", name: "Romex 12/2 NM-B 250'",
    category: "Electrical", subcategory: "Wire", brand: "Southwire", sku_hd: "SW-12-2-250",
    sku_lowes: null, sku_internal: null, unit: "roll",
    specifications: { gauge: "12", conductors: "2 + ground" },
    tier: "budget" as const, is_active: true,
    created_at: daysAgo(100), updated_at: daysAgo(20),
    unified_pricing: { product_id: "demo-prod-008", organization_id: "demo-org", unified_price: 89.97, hd_price: 89.97, lowes_price: 92.48, invoice_price: null, freshness: "yellow" as const, last_updated: daysAgo(20) },
  },
  {
    id: "demo-prod-009", organization_id: "demo-org", name: "TimberTech Composite Decking 16'",
    category: "Lumber", subcategory: "Composite", brand: "TimberTech", sku_hd: "TT-AZEK-16",
    sku_lowes: null, sku_internal: null, unit: "ea",
    specifications: { width: "5.5in", length: "16ft", color: "Coastline" },
    tier: "premium" as const, is_active: true,
    created_at: daysAgo(75), updated_at: daysAgo(1),
    unified_pricing: { product_id: "demo-prod-009", organization_id: "demo-org", unified_price: 44.50, hd_price: 44.50, lowes_price: 46.98, invoice_price: null, freshness: "green" as const, last_updated: daysAgo(1) },
  },
  {
    id: "demo-prod-010", organization_id: "demo-org", name: "James Hardie HardiePlank Siding",
    category: "Lumber", subcategory: "Siding", brand: "James Hardie", sku_hd: "JH-HP-CEDARMILL",
    sku_lowes: null, sku_internal: null, unit: "sqft",
    specifications: { profile: "Cedarmill", width: "8.25in", length: "12ft" },
    tier: "premium" as const, is_active: true,
    created_at: daysAgo(110), updated_at: daysAgo(25),
    unified_pricing: { product_id: "demo-prod-010", organization_id: "demo-org", unified_price: 2.15, hd_price: 2.15, lowes_price: 2.28, invoice_price: null, freshness: "yellow" as const, last_updated: daysAgo(25) },
  },
  {
    id: "demo-prod-011", organization_id: "demo-org", name: "Kohler Vault 33\" Undermount Sink",
    category: "Plumbing", subcategory: "Sinks", brand: "Kohler", sku_hd: "KH-VAULT-33",
    sku_lowes: null, sku_internal: null, unit: "ea",
    specifications: { material: "Stainless Steel", gauge: "18" },
    tier: "mid" as const, is_active: true,
    created_at: daysAgo(60), updated_at: daysAgo(5),
    unified_pricing: { product_id: "demo-prod-011", organization_id: "demo-org", unified_price: 689.0, hd_price: 689.0, lowes_price: 699.0, invoice_price: 689.0, freshness: "green" as const, last_updated: daysAgo(5) },
  },
  {
    id: "demo-prod-012", organization_id: "demo-org", name: "PEX-A Tubing 3/4\" 100ft",
    category: "Plumbing", subcategory: "Pipe", brand: "Uponor", sku_hd: "UPN-PEX-075-100",
    sku_lowes: null, sku_internal: null, unit: "roll",
    specifications: { diameter: "3/4in", material: "PEX-A", color: "Red" },
    tier: "mid" as const, is_active: true,
    created_at: daysAgo(90), updated_at: daysAgo(5),
    unified_pricing: { product_id: "demo-prod-012", organization_id: "demo-org", unified_price: 124.50, hd_price: 128.0, lowes_price: null, invoice_price: 124.50, freshness: "green" as const, last_updated: daysAgo(5) },
  },
];

// ── Subcontractors ──
export const demoSubcontractors = [
  {
    id: SUB_IDS[0], company_name: "Delta Plumbing Services", contact_name: "Ray Thompson",
    email: "ray@deltaplumbingms.com", phone: "(601) 555-0301",
    trades: ["plumbing", "gas line"], license_number: "MS-PLB-44821",
    insurance_expiry: dateOnly(daysFromNow(180)), rating: 5, notes: "Reliable, always on time. Been using them 3 years.",
    is_active: true, created_at: daysAgo(400),
  },
  {
    id: SUB_IDS[1], company_name: "Southern Electric Co.", contact_name: "Andre Williams",
    email: "andre@southernelectric.net", phone: "(601) 555-0418",
    trades: ["electrical", "low voltage"], license_number: "MS-ELC-33190",
    insurance_expiry: dateOnly(daysFromNow(90)), rating: 4, notes: "Great for residential. Commercial rates higher than average.",
    is_active: true, created_at: daysAgo(350),
  },
  {
    id: SUB_IDS[2], company_name: "Magnolia Concrete & Stone", contact_name: "Bobby Magee",
    email: "info@magnoliaconcrete.com", phone: "(601) 555-0522",
    trades: ["concrete", "countertops", "masonry"], license_number: "MS-GC-55140",
    insurance_expiry: dateOnly(daysFromNow(250)), rating: 4, notes: "Does great countertop work. 5-day lead time on fabrication.",
    is_active: true, created_at: daysAgo(280),
  },
  {
    id: SUB_IDS[3], company_name: "Gulf Coast Roofing", contact_name: "Mike Landry",
    email: "mike@gulfcoastroof.com", phone: "(228) 555-0199",
    trades: ["roofing", "gutters"], license_number: "MS-ROF-28445",
    insurance_expiry: dateOnly(daysFromNow(320)), rating: 5, notes: "Best roofer on the coast. Handles insurance claims well.",
    is_active: true, created_at: daysAgo(500),
  },
  {
    id: SUB_IDS[4], company_name: "Dixie Drywall & Finishing", contact_name: "Steve Perkins",
    email: "steve@dixiedrywall.com", phone: "(601) 555-0644",
    trades: ["drywall", "plaster", "painting"], license_number: "MS-GC-61230",
    insurance_expiry: dateOnly(daysAgo(15)), rating: 3, notes: "Decent work but insurance lapsed — need updated COI before next job.",
    is_active: true, created_at: daysAgo(200),
  },
];

// ── Sub Bids ──
export const demoSubBids = [
  { id: "demo-bid-01", estimate_id: ESTIMATE_IDS[0], subcontractor_id: SUB_IDS[0], trade: "plumbing", scope_description: "Kitchen rough-in + fixtures install", bid_amount: 3800, status: "accepted", due_date: null, notes: null, created_at: daysAgo(40) },
  { id: "demo-bid-02", estimate_id: ESTIMATE_IDS[0], subcontractor_id: SUB_IDS[1], trade: "electrical", scope_description: "Kitchen electrical — 4 new circuits, under-cab lighting", bid_amount: 2800, status: "accepted", due_date: null, notes: null, created_at: daysAgo(40) },
  { id: "demo-bid-03", estimate_id: ESTIMATE_IDS[0], subcontractor_id: SUB_IDS[2], trade: "countertops", scope_description: "Granite countertop template, fab, install — Luna Pearl 3cm", bid_amount: 4200, status: "received", due_date: dateOnly(daysFromNow(5)), notes: "Includes undermount sink cutout", created_at: daysAgo(10) },
  { id: "demo-bid-04", estimate_id: ESTIMATE_IDS[4], subcontractor_id: SUB_IDS[3], trade: "roofing", scope_description: "Full tear-off & re-roof — 22sq architectural shingles", bid_amount: 12800, status: "accepted", due_date: null, notes: null, created_at: daysAgo(14) },
  { id: "demo-bid-05", estimate_id: ESTIMATE_IDS[2], subcontractor_id: SUB_IDS[0], trade: "plumbing", scope_description: "Whole house re-pipe PEX + 2 bath rough-ins", bid_amount: 14500, status: "requested", due_date: dateOnly(daysFromNow(10)), notes: null, created_at: daysAgo(3) },
  { id: "demo-bid-06", estimate_id: ESTIMATE_IDS[2], subcontractor_id: SUB_IDS[1], trade: "electrical", scope_description: "200A panel upgrade + full house rewire", bid_amount: 18200, status: "received", due_date: dateOnly(daysFromNow(7)), notes: "Includes permit pulling", created_at: daysAgo(5) },
  { id: "demo-bid-07", estimate_id: ESTIMATE_IDS[6], subcontractor_id: SUB_IDS[2], trade: "masonry", scope_description: "Foundation pier repair — 6 piers", bid_amount: 8500, status: "draft", due_date: null, notes: "Needs site visit first", created_at: daysAgo(2) },
  { id: "demo-bid-08", estimate_id: ESTIMATE_IDS[0], subcontractor_id: SUB_IDS[4], trade: "drywall", scope_description: "Kitchen drywall — hang, tape, mud, texture", bid_amount: 1800, status: "accepted", due_date: null, notes: null, created_at: daysAgo(12) },
];

// ── Warranty Items ──
export const demoWarrantyItems = [
  {
    id: "demo-war-01", estimate_id: ESTIMATE_IDS[0], client_id: CLIENT_IDS[0],
    item_description: "Kitchen cabinet soft-close hinges", category: "material",
    warranty_start: dateOnly(daysAgo(90)), warranty_end: dateOnly(daysFromNow(275)),
    status: "active", claimed_at: null, claim_description: null,
    resolution: null, resolved_at: null, cost_to_repair: null,
    callback_date: null, callback_notes: null, created_at: daysAgo(90),
  },
  {
    id: "demo-war-02", estimate_id: ESTIMATE_IDS[0], client_id: CLIENT_IDS[0],
    item_description: "Granite countertop seal coat", category: "material",
    warranty_start: dateOnly(daysAgo(60)), warranty_end: dateOnly(daysFromNow(305)),
    status: "active", claimed_at: null, claim_description: null,
    resolution: null, resolved_at: null, cost_to_repair: null,
    callback_date: null, callback_notes: "Remind client to reseal every 12 months", created_at: daysAgo(60),
  },
  {
    id: "demo-war-03", estimate_id: ESTIMATE_IDS[4], client_id: CLIENT_IDS[4],
    item_description: "Roof shingle installation workmanship", category: "roofing",
    warranty_start: dateOnly(daysAgo(8)), warranty_end: dateOnly(daysFromNow(357)),
    status: "active", claimed_at: null, claim_description: null,
    resolution: null, resolved_at: null, cost_to_repair: null,
    callback_date: null, callback_notes: null, created_at: daysAgo(8),
  },
  {
    id: "demo-war-04", estimate_id: ESTIMATE_IDS[0], client_id: CLIENT_IDS[0],
    item_description: "Tile backsplash grout integrity", category: "labor",
    warranty_start: dateOnly(daysAgo(45)), warranty_end: dateOnly(daysFromNow(45)),
    status: "active", claimed_at: null, claim_description: null,
    resolution: null, resolved_at: null, cost_to_repair: null,
    callback_date: dateOnly(daysFromNow(30)), callback_notes: "Check grout lines at 90-day mark",
    created_at: daysAgo(45),
  },
  {
    id: "demo-war-05", estimate_id: ESTIMATE_IDS[5], client_id: CLIENT_IDS[5],
    item_description: "Shower pan waterproofing membrane", category: "plumbing",
    warranty_start: dateOnly(daysAgo(120)), warranty_end: dateOnly(daysFromNow(20)),
    status: "active", claimed_at: null, claim_description: null,
    resolution: null, resolved_at: null, cost_to_repair: null,
    callback_date: null, callback_notes: "Kerdi membrane — manufacturer warranty separate",
    created_at: daysAgo(120),
  },
  {
    id: "demo-war-06", estimate_id: ESTIMATE_IDS[0], client_id: CLIENT_IDS[0],
    item_description: "Kitchen faucet installation", category: "plumbing",
    warranty_start: dateOnly(daysAgo(200)), warranty_end: dateOnly(daysAgo(15)),
    status: "expired", claimed_at: null, claim_description: null,
    resolution: null, resolved_at: null, cost_to_repair: null,
    callback_date: null, callback_notes: null, created_at: daysAgo(200),
  },
  {
    id: "demo-war-07", estimate_id: ESTIMATE_IDS[4], client_id: CLIENT_IDS[4],
    item_description: "Flashing around chimney", category: "roofing",
    warranty_start: dateOnly(daysAgo(150)), warranty_end: dateOnly(daysAgo(2)),
    status: "claimed", claimed_at: dateOnly(daysAgo(5)),
    claim_description: "Minor leak at chimney flashing during heavy rain",
    resolution: "Resealed flashing with new ice & water shield", resolved_at: dateOnly(daysAgo(2)),
    cost_to_repair: 350.00,
    callback_date: null, callback_notes: null, created_at: daysAgo(150),
  },
  {
    id: "demo-war-08", estimate_id: ESTIMATE_IDS[2], client_id: CLIENT_IDS[2],
    item_description: "Electrical panel upgrade workmanship", category: "electrical",
    warranty_start: dateOnly(daysAgo(30)), warranty_end: dateOnly(daysFromNow(335)),
    status: "active", claimed_at: null, claim_description: null,
    resolution: null, resolved_at: null, cost_to_repair: null,
    callback_date: null, callback_notes: null, created_at: daysAgo(30),
  },
];

// ── Job Actuals (for FinancialReportsPage) ──
export const demoJobActuals = [
  {
    id: "demo-ja-01", organization_id: "demo-org", estimate_id: ESTIMATE_IDS[0],
    actual_materials: 19200, actual_labor: 13800, actual_subs: 8600,
    actual_total: 41600, actual_duration_days: 28,
    actual_margin_pct: 13.1, variance_materials: 700, variance_labor: -400,
    variance_total: 2700, notes: "Slight material overrun on tile — client changed selection mid-job",
    completed_at: null, created_at: daysAgo(5),
  },
  {
    id: "demo-ja-02", organization_id: "demo-org", estimate_id: ESTIMATE_IDS[4],
    actual_materials: 10100, actual_labor: 7800, actual_subs: 0,
    actual_total: 17900, actual_duration_days: 12,
    actual_margin_pct: 26.0, variance_materials: 300, variance_labor: -600,
    variance_total: -1900, notes: "Came in under budget. 3 decking sheets extra wasn't as bad as quoted.",
    completed_at: null, created_at: daysAgo(2),
  },
  {
    id: "demo-ja-03", organization_id: "demo-org", estimate_id: ESTIMATE_IDS[9],
    actual_materials: 1050, actual_labor: 2400, actual_subs: 0,
    actual_total: 3450, actual_duration_days: 5,
    actual_margin_pct: 1.4, variance_materials: -150, variance_labor: -400,
    variance_total: -750, notes: "Tight margin as expected on paint jobs",
    completed_at: daysAgo(12), created_at: daysAgo(12),
  },
  {
    id: "demo-ja-04", organization_id: "demo-org", estimate_id: ESTIMATE_IDS[5],
    actual_materials: 10800, actual_labor: 9200, actual_subs: 2200,
    actual_total: 22200, actual_duration_days: 18,
    actual_margin_pct: 31.5, variance_materials: -400, variance_labor: -600,
    variance_total: -3400, notes: null,
    completed_at: null, created_at: daysAgo(7),
  },
];

// ── Time Entries (for FinancialReportsPage) ──
export const demoTimeEntries = [
  { id: "demo-te-01", estimate_id: ESTIMATE_IDS[0], labor_cost: 1200, hours_worked: 8 },
  { id: "demo-te-02", estimate_id: ESTIMATE_IDS[0], labor_cost: 1400, hours_worked: 9.5 },
  { id: "demo-te-03", estimate_id: ESTIMATE_IDS[0], labor_cost: 1100, hours_worked: 7 },
  { id: "demo-te-04", estimate_id: ESTIMATE_IDS[4], labor_cost: 900, hours_worked: 6 },
  { id: "demo-te-05", estimate_id: ESTIMATE_IDS[4], labor_cost: 1050, hours_worked: 7 },
  { id: "demo-te-06", estimate_id: ESTIMATE_IDS[9], labor_cost: 600, hours_worked: 4 },
  { id: "demo-te-07", estimate_id: ESTIMATE_IDS[5], labor_cost: 1300, hours_worked: 8.5 },
  { id: "demo-te-08", estimate_id: ESTIMATE_IDS[5], labor_cost: 1100, hours_worked: 7 },
];

// ── Demo Activity Feed (for Dashboard) ──
export const demoActivityEntries = [
  { id: "demo-act-01", type: "estimate" as const, action: "accepted", description: "MHP-2026-001 — Kitchen Remodel", timestamp: daysAgo(1) },
  { id: "demo-act-02", type: "client" as const, action: "added", description: "Tony Nguyen", timestamp: daysAgo(1) },
  { id: "demo-act-03", type: "invoice" as const, action: "processing", description: "Home Depot HD-4501293", timestamp: daysAgo(1) },
  { id: "demo-act-04", type: "estimate" as const, action: "sent", description: "MHP-2026-006 — Master Bathroom Renovation", timestamp: daysAgo(2) },
  { id: "demo-act-05", type: "estimate" as const, action: "created", description: "MHP-2026-012 — Siding Replacement", timestamp: daysAgo(3) },
  { id: "demo-act-06", type: "client" as const, action: "added", description: "Patricia Holloway", timestamp: daysAgo(3) },
  { id: "demo-act-07", type: "invoice" as const, action: "confirmed", description: "84 Lumber 84L-20260228", timestamp: daysAgo(4) },
  { id: "demo-act-08", type: "estimate" as const, action: "in_review", description: "MHP-2026-007 — Historic Home Restoration", timestamp: daysAgo(4) },
  { id: "demo-act-09", type: "estimate" as const, action: "accepted", description: "MHP-2026-005 — Storm Damage Roof Repair", timestamp: daysAgo(5) },
  { id: "demo-act-10", type: "client" as const, action: "added", description: "Dwayne Mitchell", timestamp: daysAgo(5) },
  { id: "demo-act-11", type: "invoice" as const, action: "confirmed", description: "Home Depot HD-4492817", timestamp: daysAgo(6) },
  { id: "demo-act-12", type: "estimate" as const, action: "created", description: "MHP-2026-008 — Restaurant Build-Out", timestamp: daysAgo(6) },
];

// ── Team Members (for Settings > Team) ──
export const demoTeamMembers = [
  { name: "James Walton", role: "owner", email: "james@northmshomepros.com", status: "active" },
  { name: "Marcus Thompson", role: "estimator", email: "marcus.t@northmshomepros.com", status: "active" },
  { name: "Devon Lewis", role: "field_tech", email: "devon.l@northmshomepros.com", status: "active" },
  { name: "Sarah Mitchell", role: "pm", email: "sarah.m@northmshomepros.com", status: "active" },
];
