/**
 * MHP Historical Pricing Database
 * Extracted from 3 years of construction estimates (2023-2026)
 * 240 project files, 28,941 line items analyzed
 * Auto-generated — do not edit manually
 */

export interface HistoricalPriceEntry {
  name: string;
  category: string;
  occurrences: number;
  projectsUsed: number;
  projectTypes: string[];
  pricing: { avg: number; min: number; max: number; median: number };
  labor?: { avg: number; min: number; max: number };
  material?: { avg: number; min: number; max: number };
}

export const MHP_PRICING_DATABASE: HistoricalPriceEntry[] = [
  {
    name: "General Conditions",
    category: "general_conditions",
    occurrences: 116,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 2422.41, min: 250.0, max: 6500.0, median: 2000.0 },
    labor: { avg: 2627.45, min: 250.0, max: 6500.0 },
    material: { avg: 2000.0, min: 2000.0, max: 2000.0 },
  },
  {
    name: "Final Cleaning",
    category: "general_conditions",
    occurrences: 116,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1026.72, min: 100.0, max: 3500.0, median: 750.0 },
    labor: { avg: 895.95, min: 350.0, max: 1950.0 },
  },
  {
    name: "Project Coordination (Supervision)",
    category: "general_conditions",
    occurrences: 113,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 2097.35, min: 500.0, max: 3000.0, median: 1850.0 },
    labor: { avg: 4103.37, min: 300.0, max: 21700.0 },
  },
  {
    name: "Building Permits",
    category: "general_conditions",
    occurrences: 113,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1041.64, min: 50.0, max: 1550.0, median: 1215.0 },
    labor: { avg: 125.0, min: 125.0, max: 125.0 },
    material: { avg: 1215.0, min: 1215.0, max: 1215.0 },
  },
  {
    name: "Waste Management",
    category: "general_conditions",
    occurrences: 113,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 357.75, min: 50.0, max: 625.0, median: 350.0 },
    labor: { avg: 500.0, min: 500.0, max: 500.0 },
    material: { avg: 1177.0, min: 1177.0, max: 1177.0 },
  },
  {
    name: "Countertop Labor",
    category: "cabinetry_countertops",
    occurrences: 113,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1237.85, min: 17.5, max: 4000.0, median: 45.0 },
    labor: { avg: 2568.0, min: 2568.0, max: 2568.0 },
  },
  {
    name: "Architectural Plans",
    category: "general_conditions",
    occurrences: 112,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 725.89, min: 100.0, max: 3500.0, median: 675.0 },
    labor: { avg: 618.75, min: 100.0, max: 2550.0 },
    material: { avg: 675.0, min: 675.0, max: 675.0 },
  },
  {
    name: "Interior Trim Material",
    category: "interior_finish",
    occurrences: 112,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1440.42, min: 1.56, max: 3098.0, median: 6.5 },
    material: { avg: 2975.38, min: 850.0, max: 3098.0 },
  },
  {
    name: "Interior Trim Labor",
    category: "interior_finish",
    occurrences: 112,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 20.03, min: 1.5, max: 1850.0, median: 2.0 },
    labor: { avg: 4849.05, min: 455.0, max: 15500.0 },
  },
  {
    name: "Interior Doors",
    category: "interior_finish",
    occurrences: 112,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1965.25, min: 125.0, max: 3871.0, median: 450.0 },
    material: { avg: 3871.0, min: 3871.0, max: 3871.0 },
  },
  {
    name: "Drywall",
    category: "interior_finish",
    occurrences: 112,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 6337.04, min: 0.85, max: 13623.24, median: 4.75 },
    labor: { avg: 250.0, min: 250.0, max: 250.0 },
    material: { avg: 8173.94, min: 8173.94, max: 8173.94 },
  },
  {
    name: "Countertop Material",
    category: "cabinetry_countertops",
    occurrences: 112,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 2834.03, min: 17.5, max: 20000.0, median: 3852.0 },
    material: { avg: 5293.65, min: 665.0, max: 20000.0 },
  },
  {
    name: "Plumbing Fixtures",
    category: "plumbing",
    occurrences: 112,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 3138.48, min: 200.0, max: 8000.0, median: 3370.0 },
    material: { avg: 3536.94, min: 325.0, max: 6500.0 },
  },
  {
    name: "Electrical Material",
    category: "electrical",
    occurrences: 112,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 3338.68, min: 2.25, max: 6508.8, median: 1800.0 },
    labor: { avg: 2031.67, min: 325.0, max: 3500.0 },
    material: { avg: 6508.8, min: 6508.8, max: 6508.8 },
  },
  {
    name: "Lighting Fixtures",
    category: "electrical",
    occurrences: 112,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 2490.8, min: 125.0, max: 13500.0, median: 2800.0 },
    labor: { avg: 350.0, min: 350.0, max: 350.0 },
    material: { avg: 3672.14, min: 200.0, max: 13500.0 },
  },
  {
    name: "Stair Material",
    category: "interior_finish",
    occurrences: 111,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 470.32, min: 25.0, max: 883.0, median: 165.0 },
    material: { avg: 883.0, min: 883.0, max: 883.0 },
  },
  {
    name: "Stair Labor",
    category: "interior_finish",
    occurrences: 111,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 451.44, min: 65.0, max: 800.0, median: 150.0 },
    labor: { avg: 1069.77, min: 585.0, max: 3150.0 },
  },
  {
    name: "Door Hardware",
    category: "interior_finish",
    occurrences: 111,
    projectsUsed: 29,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 353.02, min: 20.0, max: 675.0, median: 85.0 },
    material: { avg: 666.04, min: 200.0, max: 675.0 },
  },
  {
    name: "Framing Labor",
    category: "framing",
    occurrences: 110,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 169.44, min: 3.5, max: 3700.0, median: 5.25 },
    labor: { avg: 3806.75, min: 550.0, max: 13750.0 },
  },
  {
    name: "Insulation Material",
    category: "insulation",
    occurrences: 110,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 952.65, min: 0.5, max: 1978.8, median: 450.0 },
    material: { avg: 1978.8, min: 1978.8, max: 1978.8 },
  },
  {
    name: "Insulation Labor",
    category: "insulation",
    occurrences: 110,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 624.19, min: 0.25, max: 1319.2, median: 1.75 },
    labor: { avg: 747.0, min: 747.0, max: 747.0 },
  },
  {
    name: "HVAC Material",
    category: "hvac",
    occurrences: 110,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 6881.37, min: 1220.59, max: 84000.0, median: 3500.0 },
    material: { avg: 7933.84, min: 7933.84, max: 7933.84 },
  },
  {
    name: "Framing Material",
    category: "framing",
    occurrences: 109,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 9831.0, min: 6.0, max: 30143.49, median: 18093.0 },
    material: { avg: 16843.32, min: 35.0, max: 18093.0 },
  },
  {
    name: "Site Prep/Grading",
    category: "sitework",
    occurrences: 108,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 3165.74, min: 400.0, max: 23500.0, median: 875.0 },
    labor: { avg: 900.0, min: 750.0, max: 2850.0 },
  },
  {
    name: "Electrical Conduit",
    category: "electrical",
    occurrences: 105,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 419.92, min: 7.0, max: 2000.0, median: 750.0 },
    labor: { avg: 750.0, min: 750.0, max: 750.0 },
    material: { avg: 12450.0, min: 12450.0, max: 12450.0 },
  },
  {
    name: "Exterior Trim Labor",
    category: "exterior",
    occurrences: 104,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 831.91, min: 1.0, max: 1950.0, median: 1500.0 },
    labor: { avg: 1454.65, min: 200.0, max: 5770.0 },
    material: { avg: 8.0, min: 8.0, max: 8.0 },
  },
  {
    name: "Progess Cleaning",
    category: "general_conditions",
    occurrences: 103,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1599.76, min: 225.0, max: 2500.0, median: 2500.0 },
    labor: { avg: 2017.39, min: 225.0, max: 2500.0 },
  },
  {
    name: "Shower Door (Included Material & Labor)",
    category: "plumbing",
    occurrences: 102,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1211.27, min: 900.0, max: 2000.0, median: 900.0 },
    material: { avg: 638.93, min: 540.0, max: 1950.0 },
  },
  {
    name: "Slab Material",
    category: "concrete_masonry",
    occurrences: 101,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 127.29, min: 55.0, max: 175.0, median: 107.0 },
    material: { avg: 10165.0, min: 10165.0, max: 10165.0 },
  },
  {
    name: "Shingle Roofing Material",
    category: "roofing",
    occurrences: 101,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 2510.95, min: 85.0, max: 4763.0, median: 4763.0 },
    material: { avg: 4659.74, min: 435.0, max: 4763.0 },
  },
  {
    name: "Shingle Roofing Labor",
    category: "roofing",
    occurrences: 101,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 85.25, min: 40.0, max: 700.0, median: 40.0 },
  },
  {
    name: "Gutter Material",
    category: "exterior",
    occurrences: 101,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 747.27, min: 4.75, max: 1430.0, median: 1419.0 },
    material: { avg: 1419.0, min: 1419.0, max: 1419.0 },
  },
  {
    name: "Exterior Doors",
    category: "exterior",
    occurrences: 101,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1376.55, min: 250.0, max: 6685.0, median: 1166.67 },
    material: { avg: 3454.73, min: 1100.0, max: 3500.01 },
  },
  {
    name: "Electrical Labor",
    category: "electrical",
    occurrences: 101,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 2264.62, min: 2.5, max: 4339.2, median: 4339.2 },
  },
  {
    name: "Temporary Power",
    category: "general_conditions",
    occurrences: 100,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 391.8, min: 40.0, max: 800.0, median: 40.0 },
    material: { avg: 200.0, min: 200.0, max: 200.0 },
  },
  {
    name: "Temporary Water",
    category: "general_conditions",
    occurrences: 100,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 250.4, min: 20.0, max: 500.0, median: 20.0 },
    material: { avg: 100.0, min: 100.0, max: 100.0 },
  },
  {
    name: "Sanitary Facilities (Port-A-Johns)",
    category: "general_conditions",
    occurrences: 100,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 102.11, min: 85.6, max: 135.0, median: 85.6 },
    material: { avg: 171.2, min: 171.2, max: 171.2 },
  },
  {
    name: "Construction Staking",
    category: "general_conditions",
    occurrences: 100,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 130.17, min: 0.35, max: 250.0, median: 250.0 },
    labor: { avg: 250.0, min: 250.0, max: 250.0 },
  },
  {
    name: "Masonry Sand",
    category: "concrete_masonry",
    occurrences: 100,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 72.95, min: 25.0, max: 85.0, median: 80.0 },
    material: { avg: 800.0, min: 800.0, max: 800.0 },
  },
  {
    name: "Gutter Labor",
    category: "exterior",
    occurrences: 100,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 494.2, min: 4.5, max: 946.0, median: 946.0 },
  },
  {
    name: "Fireplace Material",
    category: "fireplace",
    occurrences: 100,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 3020.5, min: 2000.0, max: 7000.0, median: 2500.0 },
    material: { avg: 2500.0, min: 2500.0, max: 2500.0 },
  },
  {
    name: "Kitchen Appliances",
    category: "appliances",
    occurrences: 100,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 5584.8, min: 1000.0, max: 10000.0, median: 6000.0 },
    material: { avg: 6000.0, min: 6000.0, max: 6000.0 },
  },
  {
    name: "Water Heaters",
    category: "plumbing",
    occurrences: 100,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1507.0, min: 850.0, max: 2500.0, median: 1325.0 },
    material: { avg: 1543.55, min: 850.0, max: 3900.0 },
  },
  {
    name: "Concrete Forming Material (Includes Reinforcement)",
    category: "concrete_masonry",
    occurrences: 99,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 790.88, min: 0.65, max: 1500.0, median: 1500.0 },
    material: { avg: 1500.0, min: 1500.0, max: 1500.0 },
  },
  {
    name: "Termite Pre-Treat",
    category: "specialty",
    occurrences: 99,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 0.15, min: 0.15, max: 0.25, median: 0.15 },
    material: { avg: 300.0, min: 300.0, max: 300.0 },
  },
  {
    name: "Exterior Trim Material",
    category: "exterior",
    occurrences: 98,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1313.68, min: 0.75, max: 3000.0, median: 2352.0 },
    material: { avg: 2273.22, min: 125.0, max: 2352.0 },
  },
  {
    name: "Slab Labor",
    category: "concrete_masonry",
    occurrences: 97,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 26.93, min: 1.35, max: 800.0, median: 1.35 },
  },
  {
    name: "Kitchen Cabinets",
    category: "cabinetry_countertops",
    occurrences: 97,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 8325.45, min: 175.0, max: 40000.0, median: 11342.0 },
    material: { avg: 11425.43, min: 3705.0, max: 116525.0 },
  },
  {
    name: "Exterior Brick Labor",
    category: "concrete_masonry",
    occurrences: 96,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 326.04, min: 3.0, max: 650.0, median: 300.0 },
  },
  {
    name: "Exterior Brick Material",
    category: "concrete_masonry",
    occurrences: 95,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 972.04, min: 3.0, max: 12950.0, median: 300.0 },
    material: { avg: 6404.83, min: 4000.0, max: 6624.9 },
  },
  {
    name: "Landscaping/Sodding",
    category: "sitework",
    occurrences: 75,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 4972.67, min: 5.0, max: 39500.0, median: 5000.0 },
    material: { avg: 2907.78, min: 450.0, max: 3000.0 },
  },
  {
    name: "Tile Labor",
    category: "flooring",
    occurrences: 74,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 3525.42, min: 2.0, max: 4970.15, median: 4970.15 },
    material: { avg: 2000.0, min: 2000.0, max: 2000.0 },
  },
  {
    name: "Windows",
    category: "exterior",
    occurrences: 71,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 5487.56, min: 335.0, max: 7306.0, median: 7306.0 },
    material: { avg: 7206.08, min: 2010.0, max: 7306.0 },
  },
  {
    name: "Carpet Material",
    category: "flooring",
    occurrences: 68,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 20.53, min: 15.5, max: 30.0, median: 21.11 },
    material: { avg: 2398.1, min: 2398.1, max: 2398.1 },
  },
  {
    name: "Carpet Labor",
    category: "flooring",
    occurrences: 68,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 7.75, min: 6.39, max: 15.0, median: 6.39 },
  },
  {
    name: "Plumbing Material",
    category: "plumbing",
    occurrences: 64,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 4986.33, min: 375.0, max: 6000.0, median: 6000.0 },
    material: { avg: 6000.0, min: 6000.0, max: 6000.0 },
  },
  {
    name: "Closet Shelving Labor",
    category: "interior_finish",
    occurrences: 60,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 21.92, min: 15.0, max: 50.0, median: 25.0 },
    labor: { avg: 610.71, min: 200.0, max: 875.0 },
  },
  {
    name: "Bathroom Vanities",
    category: "cabinetry_countertops",
    occurrences: 60,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 428.33, min: 165.0, max: 1850.0, median: 325.0 },
    material: { avg: 675.0, min: 675.0, max: 675.0 },
  },
  {
    name: "Interior Paint Material",
    category: "painting",
    occurrences: 59,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 23.29, min: 0.75, max: 800.0, median: 1.5 },
    material: { avg: 15509.0, min: 15509.0, max: 15509.0 },
  },
  {
    name: "Interior Paint Labor",
    category: "painting",
    occurrences: 59,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 51.33, min: 2.0, max: 2250.0, median: 3.25 },
    labor: { avg: 1976.58, min: 650.0, max: 6600.0 },
  },
  {
    name: "Pump Truck",
    category: "concrete_masonry",
    occurrences: 58,
    projectsUsed: 23,
    projectTypes: ["addition_remodel", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1954.14, min: 1800.0, max: 2250.0, median: 1880.0 },
  },
  {
    name: "Closet Shelving Material",
    category: "interior_finish",
    occurrences: 58,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 14.64, min: 10.0, max: 25.0, median: 15.0 },
    labor: { avg: 418.33, min: 120.0, max: 500.0 },
  },
  {
    name: "Mobilization",
    category: "general_conditions",
    occurrences: 57,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1888.6, min: 250.0, max: 6500.0, median: 1200.0 },
    labor: { avg: 1698.81, min: 250.0, max: 6500.0 },
  },
  {
    name: "Mantel/Wood Beam Material",
    category: "interior_finish",
    occurrences: 57,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 500.0, min: 500.0, max: 500.0, median: 500.0 },
    material: { avg: 500.0, min: 500.0, max: 500.0 },
  },
  {
    name: "Mantel/Wood Beam Labor",
    category: "interior_finish",
    occurrences: 57,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 503.51, min: 500.0, max: 550.0, median: 500.0 },
    labor: { avg: 500.0, min: 500.0, max: 500.0 },
  },
  {
    name: "Concrete Floor Staining/Scoring Labor",
    category: "concrete_masonry",
    occurrences: 56,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 3.24, min: 3.0, max: 4.75, median: 3.0 },
    labor: { avg: 4554.0, min: 4554.0, max: 4554.0 },
  },
  {
    name: "Water Service",
    category: "sitework",
    occurrences: 56,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 309.14, min: 6.0, max: 850.0, median: 300.0 },
    labor: { avg: 300.0, min: 300.0, max: 300.0 },
  },
  {
    name: "Driveway Material",
    category: "sitework",
    occurrences: 56,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 99.51, min: 1.9, max: 107.0, median: 107.0 },
    material: { avg: 1605.0, min: 1605.0, max: 1605.0 },
  },
  {
    name: "Driveway Labor",
    category: "sitework",
    occurrences: 56,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1.38, min: 1.25, max: 3.5, median: 1.25 },
  },
  {
    name: "Concrete Floor Staining/Scoring Material",
    category: "concrete_masonry",
    occurrences: 55,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1.09, min: 0.25, max: 3.25, median: 0.25 },
    material: { avg: 2185.95, min: 2185.95, max: 2185.95 },
  },
  {
    name: "Irrigation (Includes French Drains & Sprinklers)",
    category: "uncategorized",
    occurrences: 55,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1903.82, min: 30.0, max: 2000.0, median: 2000.0 },
    labor: { avg: 851.85, min: 800.0, max: 2200.0 },
    material: { avg: 1189.62, min: 650.0, max: 1200.0 },
  },
  {
    name: "Footing Material",
    category: "uncategorized",
    occurrences: 54,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1292.94, min: 8.0, max: 15600.0, median: 19.0 },
    material: { avg: 326.67, min: 280.0, max: 350.0 },
  },
  {
    name: "Shutters Material",
    category: "uncategorized",
    occurrences: 54,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 214.81, min: 80.0, max: 220.0, median: 220.0 },
    material: { avg: 1320.0, min: 1320.0, max: 1320.0 },
  },
  {
    name: "Shutters Labor",
    category: "uncategorized",
    occurrences: 54,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 99.26, min: 80.0, max: 100.0, median: 100.0 },
    labor: { avg: 600.0, min: 600.0, max: 600.0 },
  },
  {
    name: "HVAC Labor",
    category: "hvac",
    occurrences: 54,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 894.7, min: 813.73, max: 3000.0, median: 813.73 },
  },
  {
    name: "Tile Material",
    category: "flooring",
    occurrences: 54,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 4915.01, min: 4.0, max: 5103.9, median: 5103.9 },
    material: { avg: 5103.9, min: 5103.9, max: 5103.9 },
  },
  {
    name: "Alarm Installation Material",
    category: "uncategorized",
    occurrences: 53,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 645.27, min: 609.6, max: 2500.0, median: 609.6 },
    material: { avg: 609.6, min: 609.6, max: 609.6 },
  },
  {
    name: "Alarm Installation Labor",
    category: "uncategorized",
    occurrences: 53,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 445.9, min: 406.4, max: 2500.0, median: 406.4 },
  },
  {
    name: "Hardwood Labor",
    category: "uncategorized",
    occurrences: 53,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 4.24, min: 2.0, max: 4.28, median: 4.28 },
  },
  {
    name: "Builder's Risk Insurance",
    category: "uncategorized",
    occurrences: 52,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1200.0, min: 1200.0, max: 1200.0, median: 1200.0 },
    material: { avg: 1200.0, min: 1200.0, max: 1200.0 },
  },
  {
    name: "Waster/Sewer Tap Fees",
    category: "uncategorized",
    occurrences: 52,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 740.0, min: 740.0, max: 740.0, median: 740.0 },
    material: { avg: 740.0, min: 740.0, max: 740.0 },
  },
  {
    name: "Temporary Gas",
    category: "uncategorized",
    occurrences: 52,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 50.0, min: 50.0, max: 50.0, median: 50.0 },
    material: { avg: 100.0, min: 100.0, max: 100.0 },
  },
  {
    name: "Exterior Paint Material",
    category: "painting",
    occurrences: 52,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 8.82, min: 0.65, max: 100.0, median: 1.25 },
    material: { avg: 7873.8, min: 7873.8, max: 7873.8 },
  },
  {
    name: "Exterior Paint Labor",
    category: "painting",
    occurrences: 52,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 114.67, min: 1.65, max: 850.0, median: 3.0 },
    labor: { avg: 1078.11, min: 300.0, max: 6600.0 },
  },
  {
    name: "MPC",
    category: "uncategorized",
    occurrences: 52,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 10320.74, min: 10320.74, max: 10320.74, median: 10320.74 },
  },
  {
    name: "Metal Railings ($40/ft -- ESTIMATE)",
    category: "uncategorized",
    occurrences: 52,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 850.0, min: 850.0, max: 850.0, median: 850.0 },
    labor: { avg: 340.0, min: 340.0, max: 340.0 },
    material: { avg: 510.0, min: 510.0, max: 510.0 },
  },
  {
    name: "Garage Doors (Material & Labor)",
    category: "uncategorized",
    occurrences: 52,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1300.0, min: 1300.0, max: 1300.0, median: 1300.0 },
    material: { avg: 780.0, min: 780.0, max: 780.0 },
  },
  {
    name: "Hardwood Material",
    category: "uncategorized",
    occurrences: 52,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 4.28, min: 4.28, max: 4.28, median: 4.28 },
    material: { avg: 5029.0, min: 5029.0, max: 5029.0 },
  },
  {
    name: "Exterior Paint Material (NEED NEW BID)",
    category: "painting",
    occurrences: 52,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 7500.0, min: 7500.0, max: 7500.0, median: 7500.0 },
    material: { avg: 7500.0, min: 7500.0, max: 7500.0 },
  },
  {
    name: "Exterior Paint Labor (NEED NEW BID)",
    category: "painting",
    occurrences: 52,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 5000.0, min: 5000.0, max: 5000.0, median: 5000.0 },
    labor: { avg: 5000.0, min: 5000.0, max: 5000.0 },
  },
  {
    name: "Plumbing Labor",
    category: "uncategorized",
    occurrences: 52,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 4000.0, min: 4000.0, max: 4000.0, median: 4000.0 },
  },
  {
    name: "Sewer Service",
    category: "uncategorized",
    occurrences: 52,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 300.0, min: 300.0, max: 300.0, median: 300.0 },
    labor: { avg: 300.0, min: 300.0, max: 300.0 },
  },
  {
    name: "Structure Demolition",
    category: "specialty",
    occurrences: 50,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1136.5, min: 325.0, max: 3900.0, median: 600.0 },
    labor: { avg: 2078.85, min: 350.0, max: 4500.0 },
  },
  {
    name: "Wood Post & Column Labor",
    category: "uncategorized",
    occurrences: 50,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 24.1, min: 20.0, max: 125.0, median: 20.0 },
    labor: { avg: 390.0, min: 180.0, max: 600.0 },
  },
  {
    name: "Footing Labor",
    category: "uncategorized",
    occurrences: 48,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 166.18, min: 5.25, max: 2515.0, median: 8.0 },
    labor: { avg: 320.0, min: 320.0, max: 320.0 },
  },
  {
    name: "Block Labor",
    category: "uncategorized",
    occurrences: 48,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 3.02, min: 3.0, max: 4.0, median: 3.0 },
  },
  {
    name: "Block Material",
    category: "uncategorized",
    occurrences: 48,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 4.08, min: 3.0, max: 6.25, median: 4.0 },
  },
  {
    name: "Wood Post & Column Material",
    category: "uncategorized",
    occurrences: 48,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 20.42, min: 15.0, max: 125.0, median: 15.0 },
  },
  {
    name: "Fireplace Labor",
    category: "fireplace",
    occurrences: 48,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1193.75, min: 650.0, max: 2500.0, median: 750.0 },
    labor: { avg: 750.0, min: 750.0, max: 750.0 },
  },
  {
    name: "Laundry Appliances",
    category: "appliances",
    occurrences: 48,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 2659.38, min: 800.0, max: 28500.0, median: 2250.0 },
  },
  {
    name: "Electrical Meter (Permanent Power)",
    category: "uncategorized",
    occurrences: 48,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1500.0, min: 1500.0, max: 1500.0, median: 1500.0 },
  },
  {
    name: "Engineering (Site Surveys)",
    category: "general_conditions",
    occurrences: 46,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 569.57, min: 250.0, max: 1250.0, median: 450.0 },
  },
  {
    name: "Mantel Material",
    category: "interior_finish",
    occurrences: 46,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 496.74, min: 350.0, max: 500.0, median: 500.0 },
  },
  {
    name: "Mantel Labor",
    category: "interior_finish",
    occurrences: 46,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 496.74, min: 350.0, max: 500.0, median: 500.0 },
    labor: { avg: 500.0, min: 500.0, max: 500.0 },
  },
  {
    name: "Cabinet & Drawer Hardware",
    category: "cabinetry_countertops",
    occurrences: 44,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1148.28, min: 6.0, max: 3850.0, median: 850.0 },
    material: { avg: 3850.0, min: 3850.0, max: 3850.0 },
  },
  {
    name: "LVT Flooring - Labor",
    category: "uncategorized",
    occurrences: 44,
    projectsUsed: 21,
    projectTypes: ["addition_remodel", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 2.06, min: 1.5, max: 3.35, median: 1.75 },
    labor: { avg: 925.75, min: 450.0, max: 1193.5 },
  },
  {
    name: "Plumbing Material & Labor",
    category: "plumbing",
    occurrences: 44,
    projectsUsed: 21,
    projectTypes: ["addition_remodel", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 691.48, min: 350.0, max: 850.0, median: 700.0 },
  },
  {
    name: "Septic",
    category: "uncategorized",
    occurrences: 44,
    projectsUsed: 21,
    projectTypes: ["addition_remodel", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 5750.0, min: 3500.0, max: 7500.0, median: 5500.0 },
    material: { avg: 6500.0, min: 6500.0, max: 6500.0 },
  },
  {
    name: "water service",
    category: "sitework",
    occurrences: 44,
    projectsUsed: 21,
    projectTypes: ["addition_remodel", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1069.32, min: 850.0, max: 7500.0, median: 850.0 },
    material: { avg: 7500.0, min: 7500.0, max: 7500.0 },
  },
  {
    name: "Porch Material",
    category: "uncategorized",
    occurrences: 43,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 3.28, min: 3.0, max: 7.0, median: 3.0 },
  },
  {
    name: "Barn Door Kits",
    category: "uncategorized",
    occurrences: 43,
    projectsUsed: 27,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "porch"],
    pricing: { avg: 68.95, min: 30.0, max: 425.0, median: 30.0 },
  },
  {
    name: "LVT Flooring - Materials",
    category: "uncategorized",
    occurrences: 43,
    projectsUsed: 20,
    projectTypes: ["addition_remodel", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 2.52, min: 1.75, max: 4.35, median: 2.15 },
    material: { avg: 4615.94, min: 1170.0, max: 5750.0 },
  },
  {
    name: "Plumbing Gas Materials and Labor",
    category: "plumbing",
    occurrences: 43,
    projectsUsed: 20,
    projectTypes: ["addition_remodel", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 429.65, min: 350.0, max: 800.0, median: 400.0 },
  },
  {
    name: "Porch Labor",
    category: "uncategorized",
    occurrences: 37,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 3.26, min: 2.0, max: 5.0, median: 3.25 },
  },
  {
    name: "Siding Material",
    category: "exterior",
    occurrences: 31,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 9.99, min: 1.85, max: 12.0, median: 12.0 },
    material: { avg: 195.0, min: 195.0, max: 195.0 },
  },
  {
    name: "Siding Labor",
    category: "exterior",
    occurrences: 31,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 3.71, min: 2.0, max: 4.25, median: 4.0 },
    labor: { avg: 1242.5, min: 200.0, max: 2940.0 },
  },
  {
    name: "Tile Material&Labor",
    category: "flooring",
    occurrences: 31,
    projectsUsed: 19,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "commercial", "concrete_hardscape", "deck", "fencing", "general", "guest_house", "gutter", "new_build", "porch"],
    pricing: { avg: 4383.23, min: 25.0, max: 16000.0, median: 5500.0 },
    material: { avg: 4175.0, min: 2850.0, max: 5500.0 },
  },
  {
    name: "Floor Tile Labor",
    category: "flooring",
    occurrences: 30,
    projectsUsed: 14,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "fencing", "general", "new_build", "porch"],
    pricing: { avg: 4.4, min: 2.0, max: 6.5, median: 6.5 },
  },
  {
    name: "Windows&Exterior doors",
    category: "exterior",
    occurrences: 27,
    projectsUsed: 20,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "porch"],
    pricing: { avg: 459.26, min: 225.0, max: 850.0, median: 425.0 },
    material: { avg: 215.0, min: 215.0, max: 215.0 },
  },
  {
    name: "Metal Roofing Labor",
    category: "roofing",
    occurrences: 23,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 92.33, min: 1.5, max: 200.0, median: 25.0 },
  },
  {
    name: "Backsplash Material",
    category: "uncategorized",
    occurrences: 22,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 19.41, min: 6.0, max: 25.0, median: 25.0 },
    material: { avg: 534.0, min: 90.0, max: 650.0 },
  },
  {
    name: "Backsplash Labor",
    category: "uncategorized",
    occurrences: 22,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 19.5, min: 5.0, max: 25.0, median: 25.0 },
  },
  {
    name: "Foundation Waterproofing",
    category: "uncategorized",
    occurrences: 21,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 25.43, min: 1.25, max: 500.0, median: 1.25 },
  },
  {
    name: "Built-ins",
    category: "uncategorized",
    occurrences: 18,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 2520.56, min: 60.0, max: 8500.0, median: 2850.0 },
    labor: { avg: 2116.67, min: 850.0, max: 4000.0 },
    material: { avg: 22800.0, min: 22800.0, max: 22800.0 },
  },
  {
    name: "Metal Railings",
    category: "uncategorized",
    occurrences: 17,
    projectsUsed: 27,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 18039.41, min: 135.0, max: 49500.0, median: 1300.0 },
  },
  {
    name: "Floor Tile",
    category: "uncategorized",
    occurrences: 16,
    projectsUsed: 8,
    projectTypes: ["addition_remodel", "commercial", "fencing", "general", "new_build", "porch"],
    pricing: { avg: 4.44, min: 4.25, max: 4.5, median: 4.5 },
    material: { avg: 642.9, min: 204.0, max: 900.0 },
  },
  {
    name: "Segmented Block Retaining Wall",
    category: "uncategorized",
    occurrences: 15,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 3020.2, min: 6.0, max: 14905.0, median: 10.0 },
    labor: { avg: 9500.0, min: 9500.0, max: 9500.0 },
  },
  {
    name: "Plaster Labor",
    category: "uncategorized",
    occurrences: 12,
    projectsUsed: 8,
    projectTypes: ["addition_remodel", "general", "guest_house", "kitchen_renovation", "porch"],
    pricing: { avg: 1.6, min: 1.6, max: 1.6, median: 1.6 },
  },
  {
    name: "Equipment Rental",
    category: "uncategorized",
    occurrences: 12,
    projectsUsed: 8,
    projectTypes: ["barn_outbuilding", "commercial", "general", "porch"],
    pricing: { avg: 1929.17, min: 450.0, max: 3750.0, median: 1800.0 },
    material: { avg: 419.29, min: 303.93, max: 650.0 },
  },
  {
    name: "Floor Tile Matereials",
    category: "uncategorized",
    occurrences: 12,
    projectsUsed: 5,
    projectTypes: ["barn_outbuilding", "bathroom_renovation", "commercial", "general"],
    pricing: { avg: 5.0, min: 5.0, max: 5.0, median: 5.0 },
  },
  {
    name: "Mirror/Rods/Bars",
    category: "uncategorized",
    occurrences: 12,
    projectsUsed: 5,
    projectTypes: ["barn_outbuilding", "bathroom_renovation", "commercial", "general"],
    pricing: { avg: 850.0, min: 850.0, max: 850.0, median: 850.0 },
  },
  {
    name: "Garage Door",
    category: "uncategorized",
    occurrences: 11,
    projectsUsed: 5,
    projectTypes: ["commercial", "general", "new_build", "porch"],
    pricing: { avg: 1200.0, min: 1200.0, max: 1200.0, median: 1200.0 },
  },
  {
    name: "Plaster Materials",
    category: "uncategorized",
    occurrences: 11,
    projectsUsed: 7,
    projectTypes: ["addition_remodel", "general", "kitchen_renovation", "porch"],
    pricing: { avg: 0.6, min: 0.6, max: 0.6, median: 0.6 },
  },
  {
    name: "Attic Stairs",
    category: "uncategorized",
    occurrences: 10,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 315.0, min: 225.0, max: 500.0, median: 285.0 },
  },
  {
    name: "Plaster Prep Labor and Material",
    category: "uncategorized",
    occurrences: 10,
    projectsUsed: 6,
    projectTypes: ["addition_remodel", "general", "porch"],
    pricing: { avg: 0.5, min: 0.5, max: 0.5, median: 0.5 },
  },
  {
    name: "Shower Insert Option",
    category: "uncategorized",
    occurrences: 10,
    projectsUsed: 5,
    projectTypes: ["barn_outbuilding", "bathroom_renovation", "commercial", "general"],
    pricing: { avg: 2500.0, min: 2500.0, max: 2500.0, median: 2500.0 },
  },
  {
    name: "Sidewalk Material",
    category: "uncategorized",
    occurrences: 9,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 490.61, min: 2.25, max: 1200.0, median: 400.0 },
  },
  {
    name: "Sidewalk Labor",
    category: "uncategorized",
    occurrences: 9,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1568.56, min: 3.5, max: 9500.0, median: 500.0 },
  },
  {
    name: "Metal Roofing Material&Labor",
    category: "roofing",
    occurrences: 8,
    projectsUsed: 24,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "commercial", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 127.33, min: 3.4, max: 650.0, median: 56.7 },
    labor: { avg: 225.0, min: 225.0, max: 225.0 },
  },
  {
    name: "Metal Roofing Material",
    category: "roofing",
    occurrences: 8,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 14.06, min: 1.5, max: 35.0, median: 1.5 },
  },
  {
    name: "Progress Cleaning",
    category: "uncategorized",
    occurrences: 8,
    projectsUsed: 3,
    projectTypes: ["bathroom_renovation", "bonus_room", "commercial"],
    pricing: { avg: 568.75, min: 350.0, max: 1800.0, median: 350.0 },
    labor: { avg: 2435.71, min: 250.0, max: 2800.0 },
  },
  {
    name: "Metal Roofing Material Labor",
    category: "roofing",
    occurrences: 8,
    projectsUsed: 3,
    projectTypes: ["bathroom_renovation", "bonus_room", "commercial"],
    pricing: { avg: 168.75, min: 75.0, max: 200.0, median: 200.0 },
    material: { avg: 17200.0, min: 17200.0, max: 17200.0 },
  },
  {
    name: "Patio Paver",
    category: "uncategorized",
    occurrences: 8,
    projectsUsed: 3,
    projectTypes: ["concrete_hardscape", "deck", "fencing", "guest_house"],
    pricing: { avg: 7.25, min: 5.0, max: 11.0, median: 5.0 },
  },
  {
    name: "Paver Labor",
    category: "uncategorized",
    occurrences: 8,
    projectsUsed: 3,
    projectTypes: ["concrete_hardscape", "deck", "fencing", "guest_house"],
    pricing: { avg: 3.53, min: 3.25, max: 4.0, median: 3.25 },
  },
  {
    name: "Trusses & Trim Joists",
    category: "uncategorized",
    occurrences: 7,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 3863.75, min: 9.25, max: 13500.0, median: 9.25 },
  },
  {
    name: "Rental Equipment",
    category: "uncategorized",
    occurrences: 7,
    projectsUsed: 2,
    projectTypes: ["commercial", "fencing"],
    pricing: { avg: 3500.0, min: 3500.0, max: 3500.0, median: 3500.0 },
  },
  {
    name: "Shower Labor",
    category: "uncategorized",
    occurrences: 7,
    projectsUsed: 4,
    projectTypes: ["door_window", "fencing", "general"],
    pricing: { avg: 2150.18, min: 3.25, max: 10000.0, median: 16.0 },
  },
  {
    name: "Tile Materials",
    category: "flooring",
    occurrences: 7,
    projectsUsed: 5,
    projectTypes: ["door_window", "fencing", "general", "guest_house", "kitchen_renovation"],
    pricing: { avg: 6.75, min: 3.25, max: 12.0, median: 4.0 },
  },
  {
    name: "Kitchen Sink",
    category: "uncategorized",
    occurrences: 7,
    projectsUsed: 4,
    projectTypes: ["barn_outbuilding", "general", "guest_house"],
    pricing: { avg: 416.29, min: 285.0, max: 899.0, median: 300.0 },
  },
  {
    name: "Shower Fixtures",
    category: "uncategorized",
    occurrences: 7,
    projectsUsed: 4,
    projectTypes: ["barn_outbuilding", "general", "guest_house"],
    pricing: { avg: 372.14, min: 195.0, max: 450.0, median: 410.0 },
  },
  {
    name: "Bonds",
    category: "uncategorized",
    occurrences: 6,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 10000.0, min: 10000.0, max: 10000.0, median: 10000.0 },
  },
  {
    name: "Structural Steel",
    category: "uncategorized",
    occurrences: 6,
    projectsUsed: 1,
    projectTypes: ["commercial"],
    pricing: { avg: 9500.0, min: 9500.0, max: 9500.0, median: 9500.0 },
  },
  {
    name: "Trusses & Trim Joists - LVL",
    category: "uncategorized",
    occurrences: 6,
    projectsUsed: 1,
    projectTypes: ["commercial"],
    pricing: { avg: 7.0, min: 7.0, max: 7.0, median: 7.0 },
  },
  {
    name: "Wall Material",
    category: "uncategorized",
    occurrences: 6,
    projectsUsed: 1,
    projectTypes: ["commercial"],
    pricing: { avg: 15.5, min: 15.5, max: 15.5, median: 15.5 },
    material: { avg: 62000.0, min: 62000.0, max: 62000.0 },
  },
  {
    name: "Wall Labor",
    category: "uncategorized",
    occurrences: 6,
    projectsUsed: 1,
    projectTypes: ["commercial"],
    pricing: { avg: 10.25, min: 10.25, max: 10.25, median: 10.25 },
  },
  {
    name: "Epoxy Floors Materials",
    category: "uncategorized",
    occurrences: 6,
    projectsUsed: 1,
    projectTypes: ["commercial"],
    pricing: { avg: 1.95, min: 1.95, max: 1.95, median: 1.95 },
    material: { avg: 3929.25, min: 3929.25, max: 3929.25 },
  },
  {
    name: "Epoxy Floor Staining/Scoring Labor",
    category: "uncategorized",
    occurrences: 6,
    projectsUsed: 1,
    projectTypes: ["commercial"],
    pricing: { avg: 3.25, min: 3.25, max: 3.25, median: 3.25 },
  },
  {
    name: "Brick Pavers and Labor",
    category: "uncategorized",
    occurrences: 6,
    projectsUsed: 1,
    projectTypes: ["commercial"],
    pricing: { avg: 13.25, min: 13.25, max: 13.25, median: 13.25 },
    material: { avg: 5816.75, min: 5300.0, max: 6333.5 },
  },
  {
    name: "Ceiling Tiles",
    category: "uncategorized",
    occurrences: 6,
    projectsUsed: 1,
    projectTypes: ["commercial"],
    pricing: { avg: 6.5, min: 6.5, max: 6.5, median: 6.5 },
    material: { avg: 6155.5, min: 6155.5, max: 6155.5 },
  },
  {
    name: "Glass Allowance",
    category: "uncategorized",
    occurrences: 6,
    projectsUsed: 1,
    projectTypes: ["commercial"],
    pricing: { avg: 165000.0, min: 165000.0, max: 165000.0, median: 165000.0 },
    material: { avg: 165000.0, min: 165000.0, max: 165000.0 },
  },
  {
    name: "Radiation Room",
    category: "uncategorized",
    occurrences: 6,
    projectsUsed: 1,
    projectTypes: ["commercial"],
    pricing: { avg: 13500.0, min: 13500.0, max: 13500.0, median: 13500.0 },
  },
  {
    name: "Fire Suppression System",
    category: "uncategorized",
    occurrences: 6,
    projectsUsed: 1,
    projectTypes: ["commercial"],
    pricing: { avg: 55000.0, min: 55000.0, max: 55000.0, median: 55000.0 },
  },
  {
    name: "Alarms and Access",
    category: "uncategorized",
    occurrences: 6,
    projectsUsed: 1,
    projectTypes: ["commercial"],
    pricing: { avg: 17500.0, min: 17500.0, max: 17500.0, median: 17500.0 },
  },
  {
    name: "Parking Lot sidewalk",
    category: "uncategorized",
    occurrences: 6,
    projectsUsed: 1,
    projectTypes: ["commercial"],
    pricing: { avg: 6500.0, min: 6500.0, max: 6500.0, median: 6500.0 },
    material: { avg: 6500.0, min: 6500.0, max: 6500.0 },
  },
  {
    name: "Dumpster Enclosure",
    category: "uncategorized",
    occurrences: 6,
    projectsUsed: 1,
    projectTypes: ["commercial"],
    pricing: { avg: 12000.0, min: 12000.0, max: 12000.0, median: 12000.0 },
    material: { avg: 12000.0, min: 12000.0, max: 12000.0 },
  },
  {
    name: "Fencing Material",
    category: "uncategorized",
    occurrences: 6,
    projectsUsed: 2,
    projectTypes: ["concrete_hardscape", "deck", "fencing"],
    pricing: { avg: 18.33, min: 8.0, max: 25.0, median: 20.0 },
  },
  {
    name: "Fencing Labor",
    category: "uncategorized",
    occurrences: 6,
    projectsUsed: 2,
    projectTypes: ["concrete_hardscape", "deck", "fencing"],
    pricing: { avg: 273.67, min: 7.5, max: 800.0, median: 13.5 },
    labor: { avg: 691.5, min: 382.5, max: 1032.0 },
  },
  {
    name: "Subtotal",
    category: "uncategorized",
    occurrences: 6,
    projectsUsed: 1,
    projectTypes: ["general"],
    pricing: { avg: 5675.01, min: 3339.61, max: 8214.74, median: 5565.23 },
  },
  {
    name: "Foundation Moisture Barrier",
    category: "uncategorized",
    occurrences: 5,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 0.6, min: 0.25, max: 2.0, median: 0.25 },
    labor: { avg: 1056.0, min: 1056.0, max: 1056.0 },
  },
  {
    name: "Trelis Labor",
    category: "uncategorized",
    occurrences: 5,
    projectsUsed: 2,
    projectTypes: ["concrete_hardscape", "fencing", "guest_house"],
    pricing: { avg: 15.0, min: 15.0, max: 15.0, median: 15.0 },
  },
  {
    name: "Weed barrier and Instalation",
    category: "uncategorized",
    occurrences: 5,
    projectsUsed: 2,
    projectTypes: ["concrete_hardscape", "fencing", "guest_house"],
    pricing: { avg: 1.79, min: 1.1, max: 2.25, median: 2.25 },
  },
  {
    name: "Shower Tile",
    category: "uncategorized",
    occurrences: 5,
    projectsUsed: 3,
    projectTypes: ["door_window", "fencing", "general"],
    pricing: { avg: 1404.9, min: 5.0, max: 7000.0, median: 6.5 },
  },
  {
    name: "Toilet",
    category: "uncategorized",
    occurrences: 5,
    projectsUsed: 3,
    projectTypes: ["barn_outbuilding", "general"],
    pricing: { avg: 170.0, min: 125.0, max: 200.0, median: 200.0 },
  },
  {
    name: "Tub/Shower Combo",
    category: "uncategorized",
    occurrences: 5,
    projectsUsed: 2,
    projectTypes: ["barn_outbuilding", "general"],
    pricing: { avg: 418.0, min: 295.0, max: 500.0, median: 500.0 },
  },
  {
    name: "Kitchen Faucet",
    category: "uncategorized",
    occurrences: 5,
    projectsUsed: 2,
    projectTypes: ["barn_outbuilding", "general"],
    pricing: { avg: 234.0, min: 135.0, max: 300.0, median: 300.0 },
  },
  {
    name: "Vanity Faucet",
    category: "uncategorized",
    occurrences: 5,
    projectsUsed: 2,
    projectTypes: ["barn_outbuilding", "general"],
    pricing: { avg: 151.0, min: 115.0, max: 175.0, median: 175.0 },
  },
  {
    name: "Vanity Sink",
    category: "uncategorized",
    occurrences: 5,
    projectsUsed: 2,
    projectTypes: ["barn_outbuilding", "general"],
    pricing: { avg: 56.0, min: 50.0, max: 65.0, median: 50.0 },
  },
  {
    name: "Water Heater",
    category: "uncategorized",
    occurrences: 5,
    projectsUsed: 2,
    projectTypes: ["barn_outbuilding", "general"],
    pricing: { avg: 1480.0, min: 850.0, max: 1900.0, median: 1900.0 },
  },
  {
    name: "Ceiling Fans",
    category: "uncategorized",
    occurrences: 5,
    projectsUsed: 2,
    projectTypes: ["barn_outbuilding", "general"],
    pricing: { avg: 224.0, min: 185.0, max: 250.0, median: 250.0 },
  },
  {
    name: "Wall Mount Fixtures",
    category: "uncategorized",
    occurrences: 5,
    projectsUsed: 2,
    projectTypes: ["barn_outbuilding", "general"],
    pricing: { avg: 113.0, min: 95.0, max: 125.0, median: 125.0 },
  },
  {
    name: "Surface Mounts",
    category: "uncategorized",
    occurrences: 5,
    projectsUsed: 2,
    projectTypes: ["barn_outbuilding", "general"],
    pricing: { avg: 146.0, min: 65.0, max: 200.0, median: 200.0 },
  },
  {
    name: "Cabinet Lights",
    category: "uncategorized",
    occurrences: 5,
    projectsUsed: 2,
    projectTypes: ["barn_outbuilding", "general"],
    pricing: { avg: 38.0, min: 35.0, max: 40.0, median: 40.0 },
  },
  {
    name: "Data Communications",
    category: "uncategorized",
    occurrences: 4,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1125.0, min: 750.0, max: 1500.0, median: 1125.0 },
  },
  {
    name: "Gas Meter",
    category: "uncategorized",
    occurrences: 4,
    projectsUsed: 28,
    projectTypes: ["addition_remodel", "barn_outbuilding", "bathroom_renovation", "bonus_room", "commercial", "concrete_hardscape", "deck", "door_window", "fencing", "general", "guest_house", "gutter", "kitchen_renovation", "new_build", "porch"],
    pricing: { avg: 1750.0, min: 500.0, max: 3000.0, median: 1750.0 },
  },
  {
    name: "Slab",
    category: "uncategorized",
    occurrences: 4,
    projectsUsed: 2,
    projectTypes: ["addition_remodel", "general"],
    pricing: { avg: 8.5, min: 8.5, max: 8.5, median: 8.5 },
  },
  {
    name: "Environmental",
    category: "uncategorized",
    occurrences: 4,
    projectsUsed: 3,
    projectTypes: ["bathroom_renovation", "bonus_room", "general"],
    pricing: { avg: 850.0, min: 850.0, max: 850.0, median: 850.0 },
  },
  {
    name: "Pocket Doors",
    category: "uncategorized",
    occurrences: 4,
    projectsUsed: 3,
    projectTypes: ["bathroom_renovation", "bonus_room", "general"],
    pricing: { avg: 350.0, min: 350.0, max: 350.0, median: 350.0 },
  },
  {
    name: "Garage Doors",
    category: "uncategorized",
    occurrences: 4,
    projectsUsed: 3,
    projectTypes: ["bathroom_renovation", "bonus_room", "general"],
    pricing: { avg: 2450.0, min: 2450.0, max: 2450.0, median: 2450.0 },
  },
  {
    name: "Kitchen/Laundry Cabinets",
    category: "uncategorized",
    occurrences: 4,
    projectsUsed: 3,
    projectTypes: ["bathroom_renovation", "bonus_room", "general"],
    pricing: { avg: 2950.0, min: 400.0, max: 5500.0, median: 2950.0 },
  },
  {
    name: "Plumbing Material/Labor",
    category: "plumbing",
    occurrences: 4,
    projectsUsed: 3,
    projectTypes: ["bathroom_renovation", "bonus_room", "general"],
    pricing: { avg: 550.0, min: 450.0, max: 650.0, median: 550.0 },
  },
  {
    name: "Trelis Material",
    category: "uncategorized",
    occurrences: 4,
    projectsUsed: 2,
    projectTypes: ["concrete_hardscape", "fencing", "guest_house"],
    pricing: { avg: 8.25, min: 6.5, max: 10.0, median: 8.25 },
  },
  {
    name: "Firepit Stone and Metal Pit",
    category: "uncategorized",
    occurrences: 4,
    projectsUsed: 1,
    projectTypes: ["deck"],
    pricing: { avg: 2900.0, min: 800.0, max: 5000.0, median: 2900.0 },
  },
  {
    name: "Poocket Doots",
    category: "uncategorized",
    occurrences: 3,
    projectsUsed: 1,
    projectTypes: ["addition_remodel"],
    pricing: { avg: 425.0, min: 425.0, max: 425.0, median: 425.0 },
  },
  {
    name: "Concrete Removal",
    category: "uncategorized",
    occurrences: 3,
    projectsUsed: 3,
    projectTypes: ["porch"],
    pricing: { avg: 0.75, min: 0.75, max: 0.75, median: 0.75 },
  },
  {
    name: "sprinkler removal",
    category: "uncategorized",
    occurrences: 3,
    projectsUsed: 2,
    projectTypes: ["concrete_hardscape", "fencing", "guest_house"],
    pricing: { avg: 35.0, min: 35.0, max: 35.0, median: 35.0 },
  },
  {
    name: "metal gate",
    category: "uncategorized",
    occurrences: 3,
    projectsUsed: 1,
    projectTypes: ["concrete_hardscape", "fencing"],
    pricing: { avg: 1000.0, min: 1000.0, max: 1000.0, median: 1000.0 },
  },
  {
    name: "Deck Framing Material",
    category: "framing",
    occurrences: 3,
    projectsUsed: 1,
    projectTypes: ["deck"],
    pricing: { avg: 10.58, min: 8.25, max: 15.0, median: 8.5 },
  },
  {
    name: "Deck Labor",
    category: "uncategorized",
    occurrences: 3,
    projectsUsed: 1,
    projectTypes: ["deck"],
    pricing: { avg: 7.5, min: 7.5, max: 7.5, median: 7.5 },
    labor: { avg: 3787.5, min: 2280.0, max: 5295.0 },
  },
  {
    name: "Weed Barrier",
    category: "uncategorized",
    occurrences: 3,
    projectsUsed: 2,
    projectTypes: ["general"],
    pricing: { avg: 0.35, min: 0.35, max: 0.35, median: 0.35 },
  },
  {
    name: "Sand Instalaltion",
    category: "uncategorized",
    occurrences: 3,
    projectsUsed: 2,
    projectTypes: ["general"],
    pricing: { avg: 15.0, min: 15.0, max: 15.0, median: 15.0 },
  },
  {
    name: "Pea Gravel",
    category: "uncategorized",
    occurrences: 3,
    projectsUsed: 2,
    projectTypes: ["general"],
    pricing: { avg: 25.0, min: 25.0, max: 25.0, median: 25.0 },
  },
  {
    name: "Rubber Mulch",
    category: "uncategorized",
    occurrences: 3,
    projectsUsed: 2,
    projectTypes: ["general"],
    pricing: { avg: 2.25, min: 2.25, max: 2.25, median: 2.25 },
    material: { avg: 1620.0, min: 1620.0, max: 1620.0 },
  },
  {
    name: "Grass Turf",
    category: "uncategorized",
    occurrences: 3,
    projectsUsed: 2,
    projectTypes: ["general"],
    pricing: { avg: 6.93, min: 3.78, max: 8.5, median: 8.5 },
    material: { avg: 2201.0, min: 2167.5, max: 2268.0 },
  },
  {
    name: "Tub",
    category: "uncategorized",
    occurrences: 3,
    projectsUsed: 1,
    projectTypes: ["general"],
    pricing: { avg: 900.0, min: 900.0, max: 900.0, median: 900.0 },
  },
  {
    name: "Flood Lights",
    category: "uncategorized",
    occurrences: 3,
    projectsUsed: 1,
    projectTypes: ["general"],
    pricing: { avg: 25.0, min: 25.0, max: 25.0, median: 25.0 },
  },
  {
    name: "Stiebel Tankless Water Heater",
    category: "uncategorized",
    occurrences: 3,
    projectsUsed: 1,
    projectTypes: ["general", "guest_house"],
    pricing: { avg: 799.0, min: 799.0, max: 799.0, median: 799.0 },
  },
  {
    name: "Homebuild",
    category: "uncategorized",
    occurrences: 3,
    projectsUsed: 1,
    projectTypes: ["general"],
    pricing: { avg: 510000.0, min: 380000.0, max: 655000.0, median: 495000.0 },
  },
];

/** Lookup pricing by line item name */
export function lookupPrice(name: string): HistoricalPriceEntry | undefined {
  return MHP_PRICING_DATABASE.find(
    (e) => e.name.toLowerCase() === name.toLowerCase()
  );
}

/** Search pricing by partial name match */
export function searchPricing(query: string): HistoricalPriceEntry[] {
  const q = query.toLowerCase();
  return MHP_PRICING_DATABASE.filter(
    (e) => e.name.toLowerCase().includes(q)
  );
}

/** Get all items in a category */
export function getPricingByCategory(category: string): HistoricalPriceEntry[] {
  return MHP_PRICING_DATABASE.filter((e) => e.category === category);
}

/** Get all unique categories */
export function getCategories(): string[] {
  return [...new Set(MHP_PRICING_DATABASE.map((e) => e.category))];
}

/** Standard line items per project type based on historical estimates */
export const PROJECT_TYPE_TEMPLATES: Record<string, string[]> = {
  "addition_remodel": [
    "Alarm Installation Labor",
    "Alarm Installation Material",
    "Architectural Plans",
    "Attic Stairs",
    "Backsplash Labor",
    "Backsplash Material",
    "Barn Door Kits",
    "Bathroom Vanities",
    "Block Labor",
    "Block Material",
    "Bonds",
    "Builder's Risk Insurance",
    "Building Permits",
    "Built-ins",
    "Cabinet & Drawer Hardware",
    "Carpet Labor",
    "Carpet Material",
    "Closet Shelving Labor",
    "Closet Shelving Material",
    "Concrete Floor Staining/Scoring Labor",
    "Concrete Floor Staining/Scoring Material",
    "Concrete Forming Material (Includes Reinforcement)",
    "Construction Staking",
    "Countertop Labor",
    "Countertop Material",
    "Data Communications",
    "Door Hardware",
    "Driveway Labor",
    "Driveway Material",
    "Drywall",
    "Electrical Conduit",
    "Electrical Labor",
    "Electrical Material",
    "Electrical Meter (Permanent Power)",
    "Engineering (Site Surveys)",
    "Exterior Brick Labor",
    "Exterior Brick Material",
    "Exterior Doors",
    "Exterior Paint Labor",
    "Exterior Paint Labor (NEED NEW BID)",
  ],
  "barn_outbuilding": [
    "Alarm Installation Labor",
    "Alarm Installation Material",
    "Architectural Plans",
    "Attic Stairs",
    "Backsplash Labor",
    "Backsplash Material",
    "Barn Door Kits",
    "Bathroom Vanities",
    "Block Labor",
    "Block Material",
    "Bonds",
    "Builder's Risk Insurance",
    "Building Permits",
    "Built-ins",
    "Cabinet & Drawer Hardware",
    "Cabinet Lights",
    "Carpet Labor",
    "Carpet Material",
    "Ceiling Fans",
    "Closet Shelving Labor",
    "Closet Shelving Material",
    "Concrete Floor Staining/Scoring Labor",
    "Concrete Floor Staining/Scoring Material",
    "Concrete Forming Material (Includes Reinforcement)",
    "Construction Staking",
    "Countertop Labor",
    "Countertop Material",
    "Data Communications",
    "Door Hardware",
    "Driveway Labor",
    "Driveway Material",
    "Drywall",
    "Electrical Conduit",
    "Electrical Labor",
    "Electrical Material",
    "Electrical Meter (Permanent Power)",
    "Engineering (Site Surveys)",
    "Equipment Rental",
    "Exterior Brick Labor",
    "Exterior Brick Material",
  ],
  "bathroom_renovation": [
    "Alarm Installation Labor",
    "Alarm Installation Material",
    "Architectural Plans",
    "Attic Stairs",
    "Backsplash Labor",
    "Backsplash Material",
    "Barn Door Kits",
    "Bathroom Vanities",
    "Block Labor",
    "Block Material",
    "Bonds",
    "Builder's Risk Insurance",
    "Building Permits",
    "Built-ins",
    "Cabinet & Drawer Hardware",
    "Carpet Labor",
    "Carpet Material",
    "Closet Shelving Labor",
    "Closet Shelving Material",
    "Concrete Floor Staining/Scoring Labor",
    "Concrete Floor Staining/Scoring Material",
    "Concrete Forming Material (Includes Reinforcement)",
    "Construction Staking",
    "Countertop Labor",
    "Countertop Material",
    "Data Communications",
    "Door Hardware",
    "Driveway Labor",
    "Driveway Material",
    "Drywall",
    "Electrical Conduit",
    "Electrical Labor",
    "Electrical Material",
    "Electrical Meter (Permanent Power)",
    "Engineering (Site Surveys)",
    "Environmental",
    "Exterior Brick Labor",
    "Exterior Brick Material",
    "Exterior Doors",
    "Exterior Paint Labor",
  ],
  "bonus_room": [
    "Alarm Installation Labor",
    "Alarm Installation Material",
    "Architectural Plans",
    "Attic Stairs",
    "Backsplash Labor",
    "Backsplash Material",
    "Barn Door Kits",
    "Bathroom Vanities",
    "Block Labor",
    "Block Material",
    "Bonds",
    "Builder's Risk Insurance",
    "Building Permits",
    "Built-ins",
    "Cabinet & Drawer Hardware",
    "Carpet Labor",
    "Carpet Material",
    "Closet Shelving Labor",
    "Closet Shelving Material",
    "Concrete Floor Staining/Scoring Labor",
    "Concrete Floor Staining/Scoring Material",
    "Concrete Forming Material (Includes Reinforcement)",
    "Construction Staking",
    "Countertop Labor",
    "Countertop Material",
    "Data Communications",
    "Door Hardware",
    "Driveway Labor",
    "Driveway Material",
    "Drywall",
    "Electrical Conduit",
    "Electrical Labor",
    "Electrical Material",
    "Electrical Meter (Permanent Power)",
    "Engineering (Site Surveys)",
    "Environmental",
    "Exterior Brick Labor",
    "Exterior Brick Material",
    "Exterior Doors",
    "Exterior Paint Labor",
  ],
  "commercial": [
    "Alarm Installation Labor",
    "Alarm Installation Material",
    "Alarms and Access",
    "Architectural Plans",
    "Attic Stairs",
    "Backsplash Labor",
    "Backsplash Material",
    "Barn Door Kits",
    "Bathroom Vanities",
    "Block Labor",
    "Block Material",
    "Bonds",
    "Brick Pavers and Labor",
    "Builder's Risk Insurance",
    "Building Permits",
    "Built-ins",
    "Cabinet & Drawer Hardware",
    "Carpet Labor",
    "Carpet Material",
    "Ceiling Tiles",
    "Closet Shelving Labor",
    "Closet Shelving Material",
    "Concrete Floor Staining/Scoring Labor",
    "Concrete Floor Staining/Scoring Material",
    "Concrete Forming Material (Includes Reinforcement)",
    "Construction Staking",
    "Countertop Labor",
    "Countertop Material",
    "Data Communications",
    "Door Hardware",
    "Driveway Labor",
    "Driveway Material",
    "Drywall",
    "Dumpster Enclosure",
    "Electrical Conduit",
    "Electrical Labor",
    "Electrical Material",
    "Electrical Meter (Permanent Power)",
    "Engineering (Site Surveys)",
    "Epoxy Floor Staining/Scoring Labor",
  ],
  "concrete_hardscape": [
    "Alarm Installation Labor",
    "Alarm Installation Material",
    "Architectural Plans",
    "Attic Stairs",
    "Backsplash Labor",
    "Backsplash Material",
    "Barn Door Kits",
    "Bathroom Vanities",
    "Block Labor",
    "Block Material",
    "Bonds",
    "Builder's Risk Insurance",
    "Building Permits",
    "Built-ins",
    "Cabinet & Drawer Hardware",
    "Carpet Labor",
    "Carpet Material",
    "Closet Shelving Labor",
    "Closet Shelving Material",
    "Concrete Floor Staining/Scoring Labor",
    "Concrete Floor Staining/Scoring Material",
    "Concrete Forming Material (Includes Reinforcement)",
    "Construction Staking",
    "Countertop Labor",
    "Countertop Material",
    "Data Communications",
    "Door Hardware",
    "Driveway Labor",
    "Driveway Material",
    "Drywall",
    "Electrical Conduit",
    "Electrical Labor",
    "Electrical Material",
    "Electrical Meter (Permanent Power)",
    "Engineering (Site Surveys)",
    "Exterior Brick Labor",
    "Exterior Brick Material",
    "Exterior Doors",
    "Exterior Paint Labor",
    "Exterior Paint Labor (NEED NEW BID)",
  ],
  "deck": [
    "Alarm Installation Labor",
    "Alarm Installation Material",
    "Architectural Plans",
    "Attic Stairs",
    "Backsplash Labor",
    "Backsplash Material",
    "Barn Door Kits",
    "Bathroom Vanities",
    "Block Labor",
    "Block Material",
    "Bonds",
    "Builder's Risk Insurance",
    "Building Permits",
    "Built-ins",
    "Cabinet & Drawer Hardware",
    "Carpet Labor",
    "Carpet Material",
    "Closet Shelving Labor",
    "Closet Shelving Material",
    "Concrete Floor Staining/Scoring Labor",
    "Concrete Floor Staining/Scoring Material",
    "Concrete Forming Material (Includes Reinforcement)",
    "Construction Staking",
    "Countertop Labor",
    "Countertop Material",
    "Data Communications",
    "Deck Framing Material",
    "Deck Labor",
    "Door Hardware",
    "Driveway Labor",
    "Driveway Material",
    "Drywall",
    "Electrical Conduit",
    "Electrical Labor",
    "Electrical Material",
    "Electrical Meter (Permanent Power)",
    "Engineering (Site Surveys)",
    "Exterior Brick Labor",
    "Exterior Brick Material",
    "Exterior Doors",
  ],
  "door_window": [
    "Alarm Installation Labor",
    "Alarm Installation Material",
    "Architectural Plans",
    "Attic Stairs",
    "Backsplash Labor",
    "Backsplash Material",
    "Barn Door Kits",
    "Bathroom Vanities",
    "Block Labor",
    "Block Material",
    "Bonds",
    "Builder's Risk Insurance",
    "Building Permits",
    "Built-ins",
    "Cabinet & Drawer Hardware",
    "Carpet Labor",
    "Carpet Material",
    "Closet Shelving Labor",
    "Closet Shelving Material",
    "Concrete Floor Staining/Scoring Labor",
    "Concrete Floor Staining/Scoring Material",
    "Concrete Forming Material (Includes Reinforcement)",
    "Construction Staking",
    "Countertop Labor",
    "Countertop Material",
    "Data Communications",
    "Door Hardware",
    "Driveway Labor",
    "Driveway Material",
    "Drywall",
    "Electrical Conduit",
    "Electrical Labor",
    "Electrical Material",
    "Electrical Meter (Permanent Power)",
    "Engineering (Site Surveys)",
    "Exterior Brick Labor",
    "Exterior Brick Material",
    "Exterior Doors",
    "Exterior Paint Labor",
    "Exterior Paint Labor (NEED NEW BID)",
  ],
  "fencing": [
    "Alarm Installation Labor",
    "Alarm Installation Material",
    "Architectural Plans",
    "Attic Stairs",
    "Backsplash Labor",
    "Backsplash Material",
    "Barn Door Kits",
    "Bathroom Vanities",
    "Block Labor",
    "Block Material",
    "Bonds",
    "Builder's Risk Insurance",
    "Building Permits",
    "Built-ins",
    "Cabinet & Drawer Hardware",
    "Carpet Labor",
    "Carpet Material",
    "Closet Shelving Labor",
    "Closet Shelving Material",
    "Concrete Floor Staining/Scoring Labor",
    "Concrete Floor Staining/Scoring Material",
    "Concrete Forming Material (Includes Reinforcement)",
    "Construction Staking",
    "Countertop Labor",
    "Countertop Material",
    "Data Communications",
    "Door Hardware",
    "Driveway Labor",
    "Driveway Material",
    "Drywall",
    "Electrical Conduit",
    "Electrical Labor",
    "Electrical Material",
    "Electrical Meter (Permanent Power)",
    "Engineering (Site Surveys)",
    "Exterior Brick Labor",
    "Exterior Brick Material",
    "Exterior Doors",
    "Exterior Paint Labor",
    "Exterior Paint Labor (NEED NEW BID)",
  ],
  "general": [
    "Alarm Installation Labor",
    "Alarm Installation Material",
    "Architectural Plans",
    "Attic Stairs",
    "Backsplash Labor",
    "Backsplash Material",
    "Barn Door Kits",
    "Bathroom Vanities",
    "Block Labor",
    "Block Material",
    "Bonds",
    "Builder's Risk Insurance",
    "Building Permits",
    "Built-ins",
    "Cabinet & Drawer Hardware",
    "Cabinet Lights",
    "Carpet Labor",
    "Carpet Material",
    "Ceiling Fans",
    "Closet Shelving Labor",
    "Closet Shelving Material",
    "Concrete Floor Staining/Scoring Labor",
    "Concrete Floor Staining/Scoring Material",
    "Concrete Forming Material (Includes Reinforcement)",
    "Construction Staking",
    "Countertop Labor",
    "Countertop Material",
    "Data Communications",
    "Door Hardware",
    "Driveway Labor",
    "Driveway Material",
    "Drywall",
    "Electrical Conduit",
    "Electrical Labor",
    "Electrical Material",
    "Electrical Meter (Permanent Power)",
    "Engineering (Site Surveys)",
    "Environmental",
    "Equipment Rental",
    "Exterior Brick Labor",
  ],
  "guest_house": [
    "Alarm Installation Labor",
    "Alarm Installation Material",
    "Architectural Plans",
    "Attic Stairs",
    "Backsplash Labor",
    "Backsplash Material",
    "Barn Door Kits",
    "Bathroom Vanities",
    "Block Labor",
    "Block Material",
    "Bonds",
    "Builder's Risk Insurance",
    "Building Permits",
    "Built-ins",
    "Cabinet & Drawer Hardware",
    "Carpet Labor",
    "Carpet Material",
    "Closet Shelving Labor",
    "Closet Shelving Material",
    "Concrete Floor Staining/Scoring Labor",
    "Concrete Floor Staining/Scoring Material",
    "Concrete Forming Material (Includes Reinforcement)",
    "Construction Staking",
    "Countertop Labor",
    "Countertop Material",
    "Data Communications",
    "Door Hardware",
    "Driveway Labor",
    "Driveway Material",
    "Drywall",
    "Electrical Conduit",
    "Electrical Labor",
    "Electrical Material",
    "Electrical Meter (Permanent Power)",
    "Engineering (Site Surveys)",
    "Exterior Brick Labor",
    "Exterior Brick Material",
    "Exterior Doors",
    "Exterior Paint Labor",
    "Exterior Paint Labor (NEED NEW BID)",
  ],
  "gutter": [
    "Alarm Installation Labor",
    "Alarm Installation Material",
    "Architectural Plans",
    "Attic Stairs",
    "Backsplash Labor",
    "Backsplash Material",
    "Barn Door Kits",
    "Bathroom Vanities",
    "Block Labor",
    "Block Material",
    "Bonds",
    "Builder's Risk Insurance",
    "Building Permits",
    "Built-ins",
    "Cabinet & Drawer Hardware",
    "Carpet Labor",
    "Carpet Material",
    "Closet Shelving Labor",
    "Closet Shelving Material",
    "Concrete Floor Staining/Scoring Labor",
    "Concrete Floor Staining/Scoring Material",
    "Concrete Forming Material (Includes Reinforcement)",
    "Construction Staking",
    "Countertop Labor",
    "Countertop Material",
    "Data Communications",
    "Door Hardware",
    "Driveway Labor",
    "Driveway Material",
    "Drywall",
    "Electrical Conduit",
    "Electrical Labor",
    "Electrical Material",
    "Electrical Meter (Permanent Power)",
    "Engineering (Site Surveys)",
    "Exterior Brick Labor",
    "Exterior Brick Material",
    "Exterior Doors",
    "Exterior Paint Labor",
    "Exterior Paint Labor (NEED NEW BID)",
  ],
  "kitchen_renovation": [
    "Alarm Installation Labor",
    "Alarm Installation Material",
    "Architectural Plans",
    "Attic Stairs",
    "Backsplash Labor",
    "Backsplash Material",
    "Barn Door Kits",
    "Bathroom Vanities",
    "Block Labor",
    "Block Material",
    "Bonds",
    "Builder's Risk Insurance",
    "Building Permits",
    "Built-ins",
    "Cabinet & Drawer Hardware",
    "Carpet Labor",
    "Carpet Material",
    "Closet Shelving Labor",
    "Closet Shelving Material",
    "Concrete Floor Staining/Scoring Labor",
    "Concrete Floor Staining/Scoring Material",
    "Concrete Forming Material (Includes Reinforcement)",
    "Construction Staking",
    "Countertop Labor",
    "Countertop Material",
    "Data Communications",
    "Door Hardware",
    "Driveway Labor",
    "Driveway Material",
    "Drywall",
    "Electrical Conduit",
    "Electrical Labor",
    "Electrical Material",
    "Electrical Meter (Permanent Power)",
    "Engineering (Site Surveys)",
    "Exterior Brick Labor",
    "Exterior Brick Material",
    "Exterior Doors",
    "Exterior Paint Labor",
    "Exterior Paint Labor (NEED NEW BID)",
  ],
  "new_build": [
    "Alarm Installation Labor",
    "Alarm Installation Material",
    "Architectural Plans",
    "Attic Stairs",
    "Backsplash Labor",
    "Backsplash Material",
    "Bathroom Vanities",
    "Block Labor",
    "Block Material",
    "Bonds",
    "Builder's Risk Insurance",
    "Building Permits",
    "Built-ins",
    "Cabinet & Drawer Hardware",
    "Carpet Labor",
    "Carpet Material",
    "Closet Shelving Labor",
    "Closet Shelving Material",
    "Concrete Floor Staining/Scoring Labor",
    "Concrete Floor Staining/Scoring Material",
    "Concrete Forming Material (Includes Reinforcement)",
    "Construction Staking",
    "Countertop Labor",
    "Countertop Material",
    "Data Communications",
    "Door Hardware",
    "Driveway Labor",
    "Driveway Material",
    "Drywall",
    "Electrical Conduit",
    "Electrical Labor",
    "Electrical Material",
    "Electrical Meter (Permanent Power)",
    "Engineering (Site Surveys)",
    "Exterior Brick Labor",
    "Exterior Brick Material",
    "Exterior Doors",
    "Exterior Paint Labor",
    "Exterior Paint Labor (NEED NEW BID)",
    "Exterior Paint Material",
  ],
  "porch": [
    "Alarm Installation Labor",
    "Alarm Installation Material",
    "Architectural Plans",
    "Attic Stairs",
    "Backsplash Labor",
    "Backsplash Material",
    "Barn Door Kits",
    "Bathroom Vanities",
    "Block Labor",
    "Block Material",
    "Bonds",
    "Builder's Risk Insurance",
    "Building Permits",
    "Built-ins",
    "Cabinet & Drawer Hardware",
    "Carpet Labor",
    "Carpet Material",
    "Closet Shelving Labor",
    "Closet Shelving Material",
    "Concrete Floor Staining/Scoring Labor",
    "Concrete Floor Staining/Scoring Material",
    "Concrete Forming Material (Includes Reinforcement)",
    "Concrete Removal",
    "Construction Staking",
    "Countertop Labor",
    "Countertop Material",
    "Data Communications",
    "Door Hardware",
    "Driveway Labor",
    "Driveway Material",
    "Drywall",
    "Electrical Conduit",
    "Electrical Labor",
    "Electrical Material",
    "Electrical Meter (Permanent Power)",
    "Engineering (Site Surveys)",
    "Equipment Rental",
    "Exterior Brick Labor",
    "Exterior Brick Material",
    "Exterior Doors",
  ],
};