/**
 * MHP Project Type Templates
 * Standard scope items and line items per project type
 * Derived from 3 years of MHP construction estimates (2023-2026)
 */

export interface ProjectTemplate {
  type: string;
  label: string;
  frequency: "HIGH" | "MEDIUM" | "LOW";
  defaultWasteFactor: number;
  defaultContingency: number;
  standardScopeItems: string[];
  commonAllowanceItems: string[];
  standardLineItems: string[];
  commonChangeOrders: string[];
  contractTypes: string[];
}

export const MHP_PROJECT_TEMPLATES: Record<string, ProjectTemplate> = {
  porch: {
    type: "porch",
    label: "Porch / Screened Porch",
    frequency: "HIGH",
    defaultWasteFactor: 0.10,
    defaultContingency: 0.125,
    standardScopeItems: [
      "Demolition of existing porch structure (if applicable)",
      "Foundation/footing work (concrete piers or continuous footer)",
      "Framing - porch structure, headers, posts",
      "Roofing - tie-in to existing roof structure, shingles/metal",
      "Decking/flooring material installation (composite, wood, or concrete/epoxy)",
      "Railing installation (wood, metal, or composite)",
      "Screen installation (for screened porches)",
      "Gutter installation",
      "Ceiling finish (bead board, tongue and groove, painted)",
      "Electrical - lighting, outlets, ceiling fan pre-wire",
      "Trim and finish carpentry",
      "Painting - exterior trim, ceiling, posts",
      "Concrete steps/landing",
    ],
    commonAllowanceItems: [
      "Exterior door",
      "Railing materials",
      "Gutter materials",
      "Screen materials",
      "Ceiling fan",
      "Lighting fixtures",
    ],
    standardLineItems: [
      "General Conditions",
      "Project Coordination (Supervision)",
      "Building Permits",
      "Mobilization",
      "Waste Management",
      "Structure Demolition",
      "Site Prep/Grading",
      "Slab Material",
      "Slab Labor",
      "Concrete Forming Material (Includes Reinforcement)",
      "Framing Material",
      "Framing Labor",
      "Shingle Roofing Material",
      "Shingle Roofing Labor",
      "Exterior Trim Material",
      "Exterior Trim Labor",
      "Exterior Doors",
      "Gutter Material",
      "Gutter Labor",
      "Electrical Material",
      "Electrical Labor",
      "Lighting Fixtures",
      "Interior Trim Material",
      "Interior Trim Labor",
      "Painting",
      "Final Cleaning",
    ],
    commonChangeOrders: [
      "Railing upgrade",
      "Gutter addition",
      "Exterior door upgrade",
      "Ceiling fan addition",
    ],
    contractTypes: ["Prime Construction Contract"],
  },

  deck: {
    type: "deck",
    label: "Deck / Outdoor Area",
    frequency: "HIGH",
    defaultWasteFactor: 0.10,
    defaultContingency: 0.125,
    standardScopeItems: [
      "Site preparation and grading",
      "Foundation/footing installation",
      "Structural framing",
      "Decking material installation (Trex composite or pressure treated lumber)",
      "Railing and post installation",
      "Staircase/steps construction",
      "Lighting installation",
      "Staining/sealing",
      "Hardscape elements (pavers, stone, concrete)",
      "French drain/drainage solutions",
      "Pergola or shade structure (if included)",
    ],
    commonAllowanceItems: [
      "Decking material (Trex/composite vs pressure-treated)",
      "Railing system",
      "Lighting fixtures",
      "Stain/sealant",
    ],
    standardLineItems: [
      "General Conditions",
      "Project Coordination (Supervision)",
      "Building Permits",
      "Mobilization",
      "Site Prep/Grading",
      "Concrete Forming Material (Includes Reinforcement)",
      "Slab Material",
      "Slab Labor",
      "Framing Material",
      "Framing Labor",
      "Stair Material",
      "Stair Labor",
      "Exterior Trim Material",
      "Exterior Trim Labor",
      "Electrical Material",
      "Electrical Labor",
      "Lighting Fixtures",
      "Painting",
      "Final Cleaning",
      "Waste Management",
    ],
    commonChangeOrders: [
      "Pergola addition",
      "Upgraded railing",
      "Additional lighting",
      "Drainage improvements",
    ],
    contractTypes: ["Prime Construction Contract"],
  },

  kitchen_renovation: {
    type: "kitchen_renovation",
    label: "Kitchen Renovation",
    frequency: "MEDIUM",
    defaultWasteFactor: 0.125,
    defaultContingency: 0.175,
    standardScopeItems: [
      "Demolition of existing kitchen elements",
      "Cabinet removal and new cabinet installation",
      "Countertop fabrication and installation (granite, quartz)",
      "Backsplash tile installation",
      "Plumbing - sink, faucet, garbage disposal",
      "Electrical - outlets, switches, under-cabinet lighting",
      "Vent hood installation",
      "Flooring replacement",
      "Painting",
      "Appliance installation (allowance-based)",
      "Trim and finish work",
    ],
    commonAllowanceItems: [
      "Cabinetry",
      "Countertops (granite/quartz)",
      "Flooring and tile",
      "Appliances",
      "Plumbing fixtures",
      "Lighting",
    ],
    standardLineItems: [
      "General Conditions",
      "Project Coordination (Supervision)",
      "Building Permits",
      "Structure Demolition",
      "Framing Material",
      "Framing Labor",
      "Drywall",
      "Kitchen Cabinets",
      "Cabinet & Drawer Hardware",
      "Countertop Material",
      "Countertop Labor",
      "Tile Material&Labor",
      "Plumbing Material & Labor",
      "Plumbing Fixtures",
      "Electrical Material",
      "Electrical Labor",
      "Lighting Fixtures",
      "Kitchen Appliances",
      "Interior Trim Material",
      "Interior Trim Labor",
      "Interior Paint Material",
      "Interior Paint Labor",
      "Final Cleaning",
      "Waste Management",
    ],
    commonChangeOrders: [
      "Appliance upgrade",
      "Countertop material change",
      "Additional electrical work",
      "Flooring change",
      "Vent hood upgrade",
    ],
    contractTypes: ["Prime Construction Contract", "Fixed Cost with Allowances"],
  },

  bathroom_renovation: {
    type: "bathroom_renovation",
    label: "Bathroom Renovation",
    frequency: "MEDIUM",
    defaultWasteFactor: 0.15,
    defaultContingency: 0.175,
    standardScopeItems: [
      "Demolition of existing fixtures and finishes",
      "Plumbing rough-in and fixture installation",
      "Shower construction/tile work",
      "Glass shower door installation",
      "Vanity and countertop installation",
      "Tile flooring installation",
      "Electrical - lighting, GFCI outlets, exhaust fan",
      "Drywall repair/replacement",
      "Painting",
      "Trim and finish carpentry",
      "Tub installation (if applicable)",
    ],
    commonAllowanceItems: [
      "Tile (shower and floor)",
      "Vanity/cabinets",
      "Countertops",
      "Plumbing fixtures",
      "Glass shower door",
      "Lighting",
    ],
    standardLineItems: [
      "General Conditions",
      "Project Coordination (Supervision)",
      "Building Permits",
      "Structure Demolition",
      "Framing Material",
      "Framing Labor",
      "Drywall",
      "Bathroom Vanities",
      "Countertop Material",
      "Countertop Labor",
      "Tile Material&Labor",
      "Shower Door (Included Material & Labor)",
      "Plumbing Material & Labor",
      "Plumbing Fixtures",
      "Water Heaters",
      "Electrical Material",
      "Electrical Labor",
      "Lighting Fixtures",
      "Interior Trim Material",
      "Interior Trim Labor",
      "Interior Paint Material",
      "Interior Paint Labor",
      "Final Cleaning",
      "Waste Management",
    ],
    commonChangeOrders: [
      "Shower size increase",
      "Tile upgrade",
      "Plumbing fixture upgrade",
      "Glass shower door upgrade",
    ],
    contractTypes: ["Prime Construction Contract"],
  },

  addition_remodel: {
    type: "addition_remodel",
    label: "Home Addition / Remodel",
    frequency: "MEDIUM",
    defaultWasteFactor: 0.125,
    defaultContingency: 0.175,
    standardScopeItems: [
      "Architectural plan review and permitting",
      "Foundation work (slab or crawlspace)",
      "Structural framing",
      "Roofing - tie-in to existing structure",
      "Exterior siding/brick",
      "Window and door installation",
      "Electrical rough-in and finish",
      "Plumbing rough-in and finish",
      "HVAC system extension or new installation",
      "Insulation",
      "Drywall/sheetrock installation",
      "Interior painting",
      "Ceiling finish",
      "Flooring installation",
      "Trim and finish carpentry",
      "Cabinet and countertop installation (if kitchen/bath included)",
      "Exterior painting and trim",
    ],
    commonAllowanceItems: [
      "Windows",
      "Exterior doors",
      "Cabinetry",
      "Countertops",
      "Flooring",
      "Plumbing fixtures",
      "Lighting",
      "HVAC equipment",
      "Appliances",
    ],
    standardLineItems: [
      "General Conditions",
      "Project Coordination (Supervision)",
      "Architectural Plans",
      "Building Permits",
      "Engineering (Site Surveys)",
      "Mobilization",
      "Temporary Power",
      "Temporary Water",
      "Sanitary Facilities (Port-A-Johns)",
      "Site Prep/Grading",
      "Slab Material",
      "Slab Labor",
      "Concrete Forming Material (Includes Reinforcement)",
      "Pump Truck",
      "Framing Material",
      "Framing Labor",
      "Shingle Roofing Material",
      "Shingle Roofing Labor",
      "Exterior Brick Material",
      "Exterior Brick Labor",
      "Exterior Trim Material",
      "Exterior Trim Labor",
      "Exterior Doors",
      "Windows",
      "Gutter Material",
      "Gutter Labor",
      "Insulation Material",
      "Insulation Labor",
      "Drywall",
      "Interior Trim Material",
      "Interior Trim Labor",
      "Interior Doors",
      "Door Hardware",
      "Stair Material",
      "Stair Labor",
      "Kitchen Cabinets",
      "Bathroom Vanities",
      "Countertop Material",
      "Countertop Labor",
      "Tile Material&Labor",
      "Interior Paint Material",
      "Interior Paint Labor",
      "Carpet Material",
      "Carpet Labor",
      "Plumbing Material & Labor",
      "Plumbing Fixtures",
      "Water Heaters",
      "Electrical Material",
      "Electrical Labor",
      "Electrical Conduit",
      "Lighting Fixtures",
      "HVAC Material",
      "Kitchen Appliances",
      "Laundry Appliances",
      "Closet Shelving Material",
      "Closet Shelving Labor",
      "Landscaping/Sodding",
      "Progess Cleaning",
      "Final Cleaning",
      "Waste Management",
    ],
    commonChangeOrders: [
      "Additional HVAC capacity/ductwork",
      "Additional electrical materials and labor",
      "Additional sheetrock",
      "Window upgrades",
      "Flooring labor and materials",
      "Interior painting",
      "Ceiling finish",
      "Brick and masonry changes",
      "Plumbing fixture upgrades",
    ],
    contractTypes: [
      "Prime Construction Contract",
      "Fixed Cost with Allowances",
      "Cost Plus Contract",
    ],
  },

  guest_house: {
    type: "guest_house",
    label: "Guest House / ADU",
    frequency: "MEDIUM",
    defaultWasteFactor: 0.10,
    defaultContingency: 0.175,
    standardScopeItems: [
      "City planning/permitting (ADU restrictive covenant)",
      "Site preparation and grading",
      "Foundation",
      "Full structural framing",
      "Roofing",
      "Exterior siding/finish",
      "Windows and exterior doors",
      "Electrical - full system",
      "Plumbing - full system",
      "HVAC (mini-split system)",
      "Tankless water heater",
      "Insulation",
      "Drywall",
      "Interior painting",
      "Flooring",
      "Kitchen cabinetry and countertops",
      "Bathroom tile and fixtures",
      "Trim and finish carpentry",
    ],
    commonAllowanceItems: [
      "Cabinets and countertops",
      "Flooring and tile",
      "Plumbing fixtures",
      "Appliances",
      "HVAC system",
      "Lighting",
    ],
    standardLineItems: [
      "General Conditions",
      "Project Coordination (Supervision)",
      "Architectural Plans",
      "Building Permits",
      "Engineering (Site Surveys)",
      "Construction Staking",
      "Mobilization",
      "Temporary Power",
      "Temporary Water",
      "Sanitary Facilities (Port-A-Johns)",
      "Termite Pre-Treat",
      "Site Prep/Grading",
      "Slab Material",
      "Slab Labor",
      "Concrete Forming Material (Includes Reinforcement)",
      "Pump Truck",
      "Masonry Sand",
      "Framing Material",
      "Framing Labor",
      "Shingle Roofing Material",
      "Shingle Roofing Labor",
      "Exterior Brick Material",
      "Exterior Brick Labor",
      "Exterior Trim Material",
      "Exterior Trim Labor",
      "Exterior Doors",
      "Windows",
      "Gutter Material",
      "Gutter Labor",
      "Insulation Material",
      "Insulation Labor",
      "Drywall",
      "Interior Trim Material",
      "Interior Trim Labor",
      "Interior Doors",
      "Door Hardware",
      "Stair Material",
      "Stair Labor",
      "Kitchen Cabinets",
      "Bathroom Vanities",
      "Cabinet & Drawer Hardware",
      "Countertop Material",
      "Countertop Labor",
      "Tile Material&Labor",
      "Shower Door (Included Material & Labor)",
      "Fireplace Material",
      "Fireplace Labor",
      "Interior Paint Material",
      "Interior Paint Labor",
      "Carpet Material",
      "Carpet Labor",
      "Concrete Floor Staining/Scoring Labor",
      "Mantel/Wood Beam Material",
      "Mantel/Wood Beam Labor",
      "Closet Shelving Material",
      "Closet Shelving Labor",
      "Plumbing Material & Labor",
      "Plumbing Gas Materials and Labor",
      "Plumbing Fixtures",
      "Water Heaters",
      "Electrical Material",
      "Electrical Labor",
      "Electrical Conduit",
      "Lighting Fixtures",
      "HVAC Material",
      "Kitchen Appliances",
      "Laundry Appliances",
      "Driveway Material",
      "Landscaping/Sodding",
      "Progess Cleaning",
      "Final Cleaning",
      "Waste Management",
    ],
    commonChangeOrders: [
      "HVAC upgrade",
      "Cabinetry upgrade",
      "Countertop upgrade",
      "Shower size change",
    ],
    contractTypes: [
      "Prime Construction Contract",
      "Fixed Cost with Allowances",
    ],
  },

  new_build: {
    type: "new_build",
    label: "New Home Build",
    frequency: "MEDIUM",
    defaultWasteFactor: 0.10,
    defaultContingency: 0.15,
    standardScopeItems: [
      "Land clearing (separate estimate)",
      "House pad and utilities infrastructure",
      "Foundation",
      "Full structural framing",
      "Roofing",
      "Exterior finish (siding, brick, stone)",
      "Windows and doors",
      "Full electrical system",
      "Full plumbing system",
      "HVAC system",
      "Insulation",
      "Drywall",
      "Interior finish (paint, trim, doors)",
      "Flooring",
      "Cabinetry and countertops",
      "All bathroom and kitchen fixtures",
      "Exterior concrete (driveway, walkways)",
      "Landscaping grading",
    ],
    commonAllowanceItems: [
      "All cabinetry",
      "All countertops",
      "All flooring",
      "All plumbing fixtures",
      "All lighting fixtures",
      "All appliances",
      "HVAC system",
      "Windows",
      "Exterior doors",
      "Interior doors",
      "Hardware",
    ],
    standardLineItems: [
      "General Conditions",
      "Project Coordination (Supervision)",
      "Architectural Plans",
      "Building Permits",
      "Engineering (Site Surveys)",
      "Construction Staking",
      "Mobilization",
      "Temporary Power",
      "Temporary Water",
      "Sanitary Facilities (Port-A-Johns)",
      "Termite Pre-Treat",
      "Site Prep/Grading",
      "Slab Material",
      "Slab Labor",
      "Concrete Forming Material (Includes Reinforcement)",
      "Pump Truck",
      "Masonry Sand",
      "Framing Material",
      "Framing Labor",
      "Shingle Roofing Material",
      "Shingle Roofing Labor",
      "Exterior Brick Material",
      "Exterior Brick Labor",
      "Exterior Trim Material",
      "Exterior Trim Labor",
      "Exterior Doors",
      "Windows",
      "Garage Door",
      "Gutter Material",
      "Gutter Labor",
      "Insulation Material",
      "Insulation Labor",
      "Drywall",
      "Interior Trim Material",
      "Interior Trim Labor",
      "Interior Doors",
      "Door Hardware",
      "Stair Material",
      "Stair Labor",
      "Kitchen Cabinets",
      "Bathroom Vanities",
      "Cabinet & Drawer Hardware",
      "Countertop Material",
      "Countertop Labor",
      "Tile Material&Labor",
      "Shower Door (Included Material & Labor)",
      "Fireplace Material",
      "Fireplace Labor",
      "Interior Paint Material",
      "Interior Paint Labor",
      "Carpet Material",
      "Carpet Labor",
      "Concrete Floor Staining/Scoring Labor",
      "Mantel/Wood Beam Material",
      "Mantel/Wood Beam Labor",
      "Closet Shelving Material",
      "Closet Shelving Labor",
      "Plumbing Material & Labor",
      "Plumbing Gas Materials and Labor",
      "Plumbing Fixtures",
      "Water Heaters",
      "Electrical Material",
      "Electrical Labor",
      "Electrical Conduit",
      "Lighting Fixtures",
      "HVAC Material",
      "Kitchen Appliances",
      "Laundry Appliances",
      "Driveway Material",
      "Landscaping/Sodding",
      "Water Service",
      "Progess Cleaning",
      "Final Cleaning",
      "Waste Management",
    ],
    commonChangeOrders: [
      "Foundation engineering changes",
      "Framing modifications",
      "HVAC system upgrade",
      "Electrical panel upgrade",
      "Window package upgrade",
    ],
    contractTypes: [
      "Prime Construction Contract",
      "Cost Plus Contract",
      "Fixed Cost with Allowances",
    ],
  },

  garage_carport: {
    type: "garage_carport",
    label: "Garage / Carport",
    frequency: "MEDIUM",
    defaultWasteFactor: 0.10,
    defaultContingency: 0.125,
    standardScopeItems: [
      "Permitting",
      "Foundation/slab work",
      "Structural framing",
      "Roofing (metal or shingle)",
      "Siding or exterior finish",
      "Electrical (lighting, outlets)",
      "Garage door installation (if enclosed)",
      "Concrete floor/slab",
      "Painting",
    ],
    commonAllowanceItems: [
      "Garage door",
      "Roofing material",
      "Electrical fixtures",
    ],
    standardLineItems: [
      "General Conditions",
      "Project Coordination (Supervision)",
      "Building Permits",
      "Mobilization",
      "Site Prep/Grading",
      "Slab Material",
      "Slab Labor",
      "Concrete Forming Material (Includes Reinforcement)",
      "Framing Material",
      "Framing Labor",
      "Shingle Roofing Material",
      "Shingle Roofing Labor",
      "Exterior Trim Material",
      "Exterior Trim Labor",
      "Garage Door",
      "Electrical Material",
      "Electrical Labor",
      "Lighting Fixtures",
      "Painting",
      "Final Cleaning",
      "Waste Management",
    ],
    commonChangeOrders: [
      "Garage door upgrade",
      "Additional electrical circuits",
      "Insulation addition",
    ],
    contractTypes: ["Prime Construction Contract"],
  },

  retaining_wall: {
    type: "retaining_wall",
    label: "Retaining Wall",
    frequency: "MEDIUM",
    defaultWasteFactor: 0.10,
    defaultContingency: 0.15,
    standardScopeItems: [
      "Site survey and engineering",
      "Excavation and grading",
      "Footing/foundation for wall",
      "Wall construction (block, stone, or poured)",
      "Drainage system behind wall (French drain, weep holes)",
      "Backfill and compaction",
      "Cap installation",
      "Landscape restoration",
    ],
    commonAllowanceItems: [
      "Wall material (stone, block, poured)",
      "Drainage materials",
      "Cap material",
    ],
    standardLineItems: [
      "General Conditions",
      "Project Coordination (Supervision)",
      "Building Permits",
      "Engineering (Site Surveys)",
      "Mobilization",
      "Site Prep/Grading",
      "Concrete Forming Material (Includes Reinforcement)",
      "Exterior Brick Material",
      "Exterior Brick Labor",
      "Masonry Sand",
      "Landscaping/Sodding",
      "Final Cleaning",
      "Waste Management",
    ],
    commonChangeOrders: [
      "Wall height increase",
      "Additional drainage",
      "Cap material upgrade",
    ],
    contractTypes: ["Prime Construction Contract"],
  },

  fencing: {
    type: "fencing",
    label: "Fencing",
    frequency: "MEDIUM",
    defaultWasteFactor: 0.05,
    defaultContingency: 0.10,
    standardScopeItems: [
      "Site layout and marking",
      "Post hole excavation",
      "Post installation and setting",
      "Rail and picket installation",
      "Gate installation",
      "Staining/sealing or painting",
    ],
    commonAllowanceItems: [
      "Fence material (wood, composite, metal)",
      "Gate hardware",
      "Stain/sealant",
    ],
    standardLineItems: [
      "General Conditions",
      "Mobilization",
      "Site Prep/Grading",
      "Framing Material",
      "Framing Labor",
      "Painting",
      "Final Cleaning",
      "Waste Management",
    ],
    commonChangeOrders: [
      "Gate addition",
      "Fence height change",
      "Material upgrade",
    ],
    contractTypes: ["Prime Construction Contract"],
  },

  commercial: {
    type: "commercial",
    label: "Commercial Buildout / Renovation",
    frequency: "MEDIUM",
    defaultWasteFactor: 0.10,
    defaultContingency: 0.15,
    standardScopeItems: [
      "Site management/owners representative services",
      "Demolition",
      "Structural steel and metal work",
      "Concrete and foundation",
      "Framing",
      "Mechanical/Electrical/Plumbing (MEP)",
      "HVAC",
      "Drywall and ceiling systems",
      "Flooring",
      "Painting",
      "Security systems",
      "Parking lot and drainage",
      "Value engineering reviews",
    ],
    commonAllowanceItems: [
      "Flooring",
      "Fixtures",
      "HVAC equipment",
      "Electrical systems",
      "Security and access control",
    ],
    standardLineItems: [
      "General Conditions",
      "Project Coordination (Supervision)",
      "Architectural Plans",
      "Building Permits",
      "Engineering (Site Surveys)",
      "Mobilization",
      "Temporary Power",
      "Temporary Water",
      "Sanitary Facilities (Port-A-Johns)",
      "Structure Demolition",
      "Site Prep/Grading",
      "Slab Material",
      "Slab Labor",
      "Framing Material",
      "Framing Labor",
      "Drywall",
      "Interior Trim Material",
      "Interior Trim Labor",
      "Interior Doors",
      "Plumbing Material & Labor",
      "Plumbing Fixtures",
      "Electrical Material",
      "Electrical Labor",
      "Electrical Conduit",
      "Lighting Fixtures",
      "HVAC Material",
      "Interior Paint Material",
      "Interior Paint Labor",
      "Tile Material&Labor",
      "Progess Cleaning",
      "Final Cleaning",
      "Waste Management",
    ],
    commonChangeOrders: [
      "Scope expansion",
      "MEP modifications",
      "Material upgrades",
      "ADA compliance additions",
    ],
    contractTypes: [
      "Cost Plus Contract",
      "Professional Services Contract",
      "Fixed Cost with Allowances",
    ],
  },

  bonus_room: {
    type: "bonus_room",
    label: "Bonus Room Buildout",
    frequency: "LOW",
    defaultWasteFactor: 0.10,
    defaultContingency: 0.15,
    standardScopeItems: [
      "Framing modifications",
      "Insulation",
      "Drywall installation",
      "Electrical (outlets, lighting, ceiling fan)",
      "HVAC extension",
      "Flooring",
      "Painting",
      "Trim and finish carpentry",
      "Built-in shelving/storage",
      "Window installation (if needed)",
    ],
    commonAllowanceItems: [
      "Flooring",
      "Lighting",
      "Ceiling fan",
      "Built-in shelving",
    ],
    standardLineItems: [
      "General Conditions",
      "Project Coordination (Supervision)",
      "Building Permits",
      "Framing Material",
      "Framing Labor",
      "Insulation Material",
      "Insulation Labor",
      "Drywall",
      "Interior Trim Material",
      "Interior Trim Labor",
      "Interior Doors",
      "Door Hardware",
      "Electrical Material",
      "Electrical Labor",
      "Lighting Fixtures",
      "HVAC Material",
      "Interior Paint Material",
      "Interior Paint Labor",
      "Carpet Material",
      "Carpet Labor",
      "Closet Shelving Material",
      "Closet Shelving Labor",
      "Final Cleaning",
      "Waste Management",
    ],
    commonChangeOrders: [
      "HVAC ductwork extension",
      "Built-in addition",
      "Window addition",
    ],
    contractTypes: ["Prime Construction Contract"],
  },

  concrete_hardscape: {
    type: "concrete_hardscape",
    label: "Concrete / Hardscape",
    frequency: "MEDIUM",
    defaultWasteFactor: 0.05,
    defaultContingency: 0.10,
    standardScopeItems: [
      "Site preparation and grading",
      "Form work",
      "Rebar/reinforcement",
      "Concrete pour and finish",
      "Sawcuts/control joints",
      "Drainage considerations",
      "Stamped or decorative concrete (if specified)",
      "Epoxy application (for porch/patio floors)",
    ],
    commonAllowanceItems: [
      "Concrete finish type",
      "Stamped concrete pattern",
      "Epoxy coating",
    ],
    standardLineItems: [
      "General Conditions",
      "Project Coordination (Supervision)",
      "Building Permits",
      "Mobilization",
      "Site Prep/Grading",
      "Concrete Forming Material (Includes Reinforcement)",
      "Slab Material",
      "Slab Labor",
      "Pump Truck",
      "Concrete Floor Staining/Scoring Labor",
      "Final Cleaning",
      "Waste Management",
    ],
    commonChangeOrders: [
      "Additional square footage",
      "Decorative finish upgrade",
      "Drainage addition",
    ],
    contractTypes: ["Prime Construction Contract"],
  },

  roofing: {
    type: "roofing",
    label: "Roofing",
    frequency: "MEDIUM",
    defaultWasteFactor: 0.05,
    defaultContingency: 0.125,
    standardScopeItems: [
      "Tear-off existing roofing materials",
      "Inspect and repair decking/sheathing",
      "Install underlayment/ice and water shield",
      "Install new shingles or metal roofing",
      "Flash around penetrations and valleys",
      "Install ridge vent",
      "Gutter installation or reattachment",
      "Clean up and haul away debris",
    ],
    commonAllowanceItems: [
      "Shingle selection",
      "Gutter materials",
      "Ridge vent",
    ],
    standardLineItems: [
      "General Conditions",
      "Project Coordination (Supervision)",
      "Building Permits",
      "Mobilization",
      "Structure Demolition",
      "Shingle Roofing Material",
      "Shingle Roofing Labor",
      "Gutter Material",
      "Gutter Labor",
      "Final Cleaning",
      "Waste Management",
    ],
    commonChangeOrders: [
      "Decking repair/replacement",
      "Additional flashing",
      "Gutter guard addition",
    ],
    contractTypes: ["Prime Construction Contract"],
  },

  door_window: {
    type: "door_window",
    label: "Door / Window Replacement",
    frequency: "MEDIUM",
    defaultWasteFactor: 0.0,
    defaultContingency: 0.10,
    standardScopeItems: [
      "Remove existing door/window",
      "Prepare rough opening",
      "Install new unit",
      "Flash and weatherproof",
      "Install interior and exterior trim",
      "Paint/stain trim",
      "Hardware installation",
    ],
    commonAllowanceItems: [
      "Door/window unit",
      "Hardware",
      "Trim material",
    ],
    standardLineItems: [
      "General Conditions",
      "Structure Demolition",
      "Framing Material",
      "Framing Labor",
      "Exterior Doors",
      "Windows",
      "Door Hardware",
      "Exterior Trim Material",
      "Exterior Trim Labor",
      "Interior Trim Material",
      "Interior Trim Labor",
      "Painting",
      "Final Cleaning",
    ],
    commonChangeOrders: [
      "Frame repair",
      "Trim upgrade",
      "Additional weatherproofing",
    ],
    contractTypes: ["Prime Construction Contract"],
  },

  painting: {
    type: "painting",
    label: "Painting (Interior/Exterior)",
    frequency: "MEDIUM",
    defaultWasteFactor: 0.10,
    defaultContingency: 0.10,
    standardScopeItems: [
      "Surface preparation (scraping, sanding, priming)",
      "Caulking and patching",
      "Interior wall painting",
      "Ceiling painting",
      "Trim painting",
      "Exterior wall painting",
      "Exterior trim painting",
      "Staining (decks, fences)",
    ],
    commonAllowanceItems: [
      "Paint brand/quality",
      "Stain type",
    ],
    standardLineItems: [
      "General Conditions",
      "Interior Paint Material",
      "Interior Paint Labor",
      "Exterior Trim Material",
      "Exterior Trim Labor",
      "Final Cleaning",
    ],
    commonChangeOrders: [
      "Additional coats",
      "Color changes",
      "Additional rooms/areas",
    ],
    contractTypes: ["Prime Construction Contract"],
  },

  infrastructure: {
    type: "infrastructure",
    label: "Infrastructure (Site/Utility)",
    frequency: "MEDIUM",
    defaultWasteFactor: 0.10,
    defaultContingency: 0.15,
    standardScopeItems: [
      "Land clearing and grading",
      "Driveway and access road construction",
      "Temporary power and water setup",
      "Well drilling and pump installation",
      "Septic system design and installation",
      "Underground utility trenching",
      "Electrical service to meter base",
      "Water service connection",
      "Sewer/septic connection",
      "Stormwater management",
      "Erosion control measures",
    ],
    commonAllowanceItems: [
      "Well pump and pressure tank",
      "Septic tank and drain field materials",
      "Electrical transformer and meter base",
      "Underground conduit and wire",
    ],
    standardLineItems: [
      "General Conditions",
      "Project Coordination (Supervision)",
      "Engineering (Site Surveys)",
      "Soil/Perc Testing",
      "Erosion Control",
      "Land Clearing",
      "Land Clearing Labor",
      "Grading/Earthwork",
      "Grading/Earthwork Labor",
      "Fill Dirt/Hauling",
      "Driveway Material",
      "Driveway Labor",
      "Well Drilling",
      "Well Pump & Pressure Tank",
      "Well Plumbing Material",
      "Well Plumbing Labor",
      "Septic Design/Permit",
      "Septic Tank",
      "Septic Drain Field Material",
      "Septic Installation Labor",
      "Underground Plumbing Material",
      "Underground Plumbing Labor",
      "Electrical Service/Meter Base",
      "Electrical Trenching",
      "Underground Electrical Material",
      "Underground Electrical Labor",
      "Temporary Power Pole",
      "Gas Line Material",
      "Gas Line Labor",
      "Stormwater/Drainage Material",
      "Stormwater/Drainage Labor",
      "Waste Management",
    ],
    commonChangeOrders: [
      "Deeper well required",
      "Additional drain field capacity",
      "Rock encountered during trenching",
      "Upgraded electrical service",
      "Extended driveway",
    ],
    contractTypes: [
      "Prime Construction Contract",
      "Cost Plus Contract",
    ],
  },
};

/** Get template for a project type */
export function getProjectTemplate(type: string): ProjectTemplate | undefined {
  return MHP_PROJECT_TEMPLATES[type];
}

/** Get all available project types */
export function getProjectTypes(): Array<{ type: string; label: string }> {
  return Object.values(MHP_PROJECT_TEMPLATES).map((t) => ({
    type: t.type,
    label: t.label,
  }));
}
